// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: comment_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	file_service "quickflow/shared/proto/file_service"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Comment represents a single comment.
type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	ImagesUrl     []string               `protobuf:"bytes,5,rep,name=images_url,json=imagesUrl,proto3" json:"images_url,omitempty"`
	Images        []*file_service.File   `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LikeCount     int64                  `protobuf:"varint,9,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	IsLiked       bool                   `protobuf:"varint,10,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"` // This will be used to indicate whether the current user liked this comment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_comment_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_comment_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_comment_service_proto_rawDescGZIP(), []int{0}
}

func (x *Comment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Comment) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *Comment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Comment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Comment) GetImagesUrl() []string {
	if x != nil {
		return x.ImagesUrl
	}
	return nil
}

func (x *Comment) GetImages() []*file_service.File {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Comment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Comment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Comment) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Comment) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

// CommentUpdate is used to update an existing comment.
type CommentUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Files         []*file_service.File   `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"` // New files to be added or updated for the comment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentUpdate) Reset() {
	*x = CommentUpdate{}
	mi := &file_comment_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentUpdate) ProtoMessage() {}

func (x *CommentUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_comment_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentUpdate.ProtoReflect.Descriptor instead.
func (*CommentUpdate) Descriptor() ([]byte, []int) {
	return file_comment_service_proto_rawDescGZIP(), []int{1}
}

func (x *CommentUpdate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommentUpdate) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CommentUpdate) GetFiles() []*file_service.File {
	if x != nil {
		return x.Files
	}
	return nil
}

// AddCommentRequest is used to add a new comment.
type AddCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentRequest) Reset() {
	*x = AddCommentRequest{}
	mi := &file_comment_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentRequest) ProtoMessage() {}

func (x *AddCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentRequest.ProtoReflect.Descriptor instead.
func (*AddCommentRequest) Descriptor() ([]byte, []int) {
	return file_comment_service_proto_rawDescGZIP(), []int{2}
}

func (x *AddCommentRequest) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

// AddCommentResponse is the response for adding a comment.
type AddCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentResponse) Reset() {
	*x = AddCommentResponse{}
	mi := &file_comment_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentResponse) ProtoMessage() {}

func (x *AddCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentResponse.ProtoReflect.Descriptor instead.
func (*AddCommentResponse) Descriptor() ([]byte, []int) {
	return file_comment_service_proto_rawDescGZIP(), []int{3}
}

func (x *AddCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

// DeleteCommentRequest is used to delete a comment.
type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Optional: To check if the comment belongs to the user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_comment_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_comment_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCommentRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *DeleteCommentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// DeleteCommentResponse is the response for deleting a comment.
type DeleteCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_comment_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_comment_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCommentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// UpdateCommentRequest is used to update a comment's text and associated files.
type UpdateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *CommentUpdate         `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentRequest) Reset() {
	*x = UpdateCommentRequest{}
	mi := &file_comment_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentRequest) ProtoMessage() {}

func (x *UpdateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) {
	return file_comment_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCommentRequest) GetComment() *CommentUpdate {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *UpdateCommentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// UpdateCommentResponse is the response for updating a comment.
type UpdateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentResponse) Reset() {
	*x = UpdateCommentResponse{}
	mi := &file_comment_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentResponse) ProtoMessage() {}

func (x *UpdateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentResponse.ProtoReflect.Descriptor instead.
func (*UpdateCommentResponse) Descriptor() ([]byte, []int) {
	return file_comment_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

// FetchCommentsForPostRequest retrieves all comments for a specific post.
type FetchCommentsForPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	NumComments   int32                  `protobuf:"varint,2,opt,name=num_comments,json=numComments,proto3" json:"num_comments,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Timestamp for pagination
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchCommentsForPostRequest) Reset() {
	*x = FetchCommentsForPostRequest{}
	mi := &file_comment_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchCommentsForPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchCommentsForPostRequest) ProtoMessage() {}

func (x *FetchCommentsForPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchCommentsForPostRequest.ProtoReflect.Descriptor instead.
func (*FetchCommentsForPostRequest) Descriptor() ([]byte, []int) {
	return file_comment_service_proto_rawDescGZIP(), []int{8}
}

func (x *FetchCommentsForPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *FetchCommentsForPostRequest) GetNumComments() int32 {
	if x != nil {
		return x.NumComments
	}
	return 0
}

func (x *FetchCommentsForPostRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// FetchCommentsForPostResponse contains the list of comments for a specific post.
type FetchCommentsForPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchCommentsForPostResponse) Reset() {
	*x = FetchCommentsForPostResponse{}
	mi := &file_comment_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchCommentsForPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchCommentsForPostResponse) ProtoMessage() {}

func (x *FetchCommentsForPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchCommentsForPostResponse.ProtoReflect.Descriptor instead.
func (*FetchCommentsForPostResponse) Descriptor() ([]byte, []int) {
	return file_comment_service_proto_rawDescGZIP(), []int{9}
}

func (x *FetchCommentsForPostResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

// LikeCommentRequest is used to like a comment.
type LikeCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentRequest) Reset() {
	*x = LikeCommentRequest{}
	mi := &file_comment_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentRequest) ProtoMessage() {}

func (x *LikeCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentRequest.ProtoReflect.Descriptor instead.
func (*LikeCommentRequest) Descriptor() ([]byte, []int) {
	return file_comment_service_proto_rawDescGZIP(), []int{10}
}

func (x *LikeCommentRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *LikeCommentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// LikeCommentResponse is the response for liking a comment.
type LikeCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentResponse) Reset() {
	*x = LikeCommentResponse{}
	mi := &file_comment_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentResponse) ProtoMessage() {}

func (x *LikeCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentResponse.ProtoReflect.Descriptor instead.
func (*LikeCommentResponse) Descriptor() ([]byte, []int) {
	return file_comment_service_proto_rawDescGZIP(), []int{11}
}

func (x *LikeCommentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// UnlikeCommentRequest is used to unlike a comment.
type UnlikeCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeCommentRequest) Reset() {
	*x = UnlikeCommentRequest{}
	mi := &file_comment_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeCommentRequest) ProtoMessage() {}

func (x *UnlikeCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeCommentRequest.ProtoReflect.Descriptor instead.
func (*UnlikeCommentRequest) Descriptor() ([]byte, []int) {
	return file_comment_service_proto_rawDescGZIP(), []int{12}
}

func (x *UnlikeCommentRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *UnlikeCommentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// UnlikeCommentResponse is the response for unliking a comment.
type UnlikeCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeCommentResponse) Reset() {
	*x = UnlikeCommentResponse{}
	mi := &file_comment_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeCommentResponse) ProtoMessage() {}

func (x *UnlikeCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeCommentResponse.ProtoReflect.Descriptor instead.
func (*UnlikeCommentResponse) Descriptor() ([]byte, []int) {
	return file_comment_service_proto_rawDescGZIP(), []int{13}
}

func (x *UnlikeCommentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetCommentRequest retrieves a single comment by its ID.
type GetCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentRequest) Reset() {
	*x = GetCommentRequest{}
	mi := &file_comment_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentRequest) ProtoMessage() {}

func (x *GetCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentRequest.ProtoReflect.Descriptor instead.
func (*GetCommentRequest) Descriptor() ([]byte, []int) {
	return file_comment_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetCommentRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *GetCommentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetCommentResponse returns the requested comment.
type GetCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentResponse) Reset() {
	*x = GetCommentResponse{}
	mi := &file_comment_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentResponse) ProtoMessage() {}

func (x *GetCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentResponse.ProtoReflect.Descriptor instead.
func (*GetCommentResponse) Descriptor() ([]byte, []int) {
	return file_comment_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

// GetCommentFilesRequest retrieves the files associated with a comment.
type GetCommentFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentFilesRequest) Reset() {
	*x = GetCommentFilesRequest{}
	mi := &file_comment_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentFilesRequest) ProtoMessage() {}

func (x *GetCommentFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentFilesRequest.ProtoReflect.Descriptor instead.
func (*GetCommentFilesRequest) Descriptor() ([]byte, []int) {
	return file_comment_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetCommentFilesRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

// GetCommentFilesResponse returns the file URLs associated with a comment.
type GetCommentFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUrls      []string               `protobuf:"bytes,1,rep,name=file_urls,json=fileUrls,proto3" json:"file_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentFilesResponse) Reset() {
	*x = GetCommentFilesResponse{}
	mi := &file_comment_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentFilesResponse) ProtoMessage() {}

func (x *GetCommentFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentFilesResponse.ProtoReflect.Descriptor instead.
func (*GetCommentFilesResponse) Descriptor() ([]byte, []int) {
	return file_comment_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetCommentFilesResponse) GetFileUrls() []string {
	if x != nil {
		return x.FileUrls
	}
	return nil
}

type GetLastPostCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastPostCommentRequest) Reset() {
	*x = GetLastPostCommentRequest{}
	mi := &file_comment_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastPostCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastPostCommentRequest) ProtoMessage() {}

func (x *GetLastPostCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastPostCommentRequest.ProtoReflect.Descriptor instead.
func (*GetLastPostCommentRequest) Descriptor() ([]byte, []int) {
	return file_comment_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetLastPostCommentRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *GetLastPostCommentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetLastPostCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastPostCommentResponse) Reset() {
	*x = GetLastPostCommentResponse{}
	mi := &file_comment_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastPostCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastPostCommentResponse) ProtoMessage() {}

func (x *GetLastPostCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastPostCommentResponse.ProtoReflect.Descriptor instead.
func (*GetLastPostCommentResponse) Descriptor() ([]byte, []int) {
	return file_comment_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetLastPostCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type GetLikesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     string                 `protobuf:"bytes,1,opt,name=commentId,proto3" json:"commentId,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikesRequest) Reset() {
	*x = GetLikesRequest{}
	mi := &file_comment_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikesRequest) ProtoMessage() {}

func (x *GetLikesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikesRequest.ProtoReflect.Descriptor instead.
func (*GetLikesRequest) Descriptor() ([]byte, []int) {
	return file_comment_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetLikesRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *GetLikesRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetLikesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type LikeComment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetType    string                 `protobuf:"bytes,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeComment) Reset() {
	*x = LikeComment{}
	mi := &file_comment_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeComment) ProtoMessage() {}

func (x *LikeComment) ProtoReflect() protoreflect.Message {
	mi := &file_comment_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeComment.ProtoReflect.Descriptor instead.
func (*LikeComment) Descriptor() ([]byte, []int) {
	return file_comment_service_proto_rawDescGZIP(), []int{21}
}

func (x *LikeComment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LikeComment) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *LikeComment) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *LikeComment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetLikesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Likes         []*LikeComment         `protobuf:"bytes,1,rep,name=likes,proto3" json:"likes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikesResponse) Reset() {
	*x = GetLikesResponse{}
	mi := &file_comment_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikesResponse) ProtoMessage() {}

func (x *GetLikesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikesResponse.ProtoReflect.Descriptor instead.
func (*GetLikesResponse) Descriptor() ([]byte, []int) {
	return file_comment_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetLikesResponse) GetLikes() []*LikeComment {
	if x != nil {
		return x.Likes
	}
	return nil
}

var File_comment_service_proto protoreflect.FileDescriptor

const file_comment_service_proto_rawDesc = "" +
	"\n" +
	"\x15comment_service.proto\x12\x0fcomment_service\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ffile_service/file_service.proto\"\xa2\x02\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"images_url\x18\x05 \x03(\tR\timagesUrl\x12*\n" +
	"\x06images\x18\x06 \x03(\v2\x12.file_service.FileR\x06images\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"like_count\x18\t \x01(\x03R\tlikeCount\x12\x19\n" +
	"\bis_liked\x18\n" +
	" \x01(\bR\aisLiked\"]\n" +
	"\rCommentUpdate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12(\n" +
	"\x05files\x18\x03 \x03(\v2\x12.file_service.FileR\x05files\"G\n" +
	"\x11AddCommentRequest\x122\n" +
	"\acomment\x18\x01 \x01(\v2\x18.comment_service.CommentR\acomment\"H\n" +
	"\x12AddCommentResponse\x122\n" +
	"\acomment\x18\x01 \x01(\v2\x18.comment_service.CommentR\acomment\"N\n" +
	"\x14DeleteCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"1\n" +
	"\x15DeleteCommentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"i\n" +
	"\x14UpdateCommentRequest\x128\n" +
	"\acomment\x18\x01 \x01(\v2\x1e.comment_service.CommentUpdateR\acomment\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"K\n" +
	"\x15UpdateCommentResponse\x122\n" +
	"\acomment\x18\x01 \x01(\v2\x18.comment_service.CommentR\acomment\"w\n" +
	"\x1bFetchCommentsForPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12!\n" +
	"\fnum_comments\x18\x02 \x01(\x05R\vnumComments\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"T\n" +
	"\x1cFetchCommentsForPostResponse\x124\n" +
	"\bcomments\x18\x01 \x03(\v2\x18.comment_service.CommentR\bcomments\"L\n" +
	"\x12LikeCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"/\n" +
	"\x13LikeCommentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"N\n" +
	"\x14UnlikeCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"1\n" +
	"\x15UnlikeCommentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"K\n" +
	"\x11GetCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"H\n" +
	"\x12GetCommentResponse\x122\n" +
	"\acomment\x18\x01 \x01(\v2\x18.comment_service.CommentR\acomment\"7\n" +
	"\x16GetCommentFilesRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\"6\n" +
	"\x17GetCommentFilesResponse\x12\x1b\n" +
	"\tfile_urls\x18\x01 \x03(\tR\bfileUrls\"M\n" +
	"\x19GetLastPostCommentRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"P\n" +
	"\x1aGetLastPostCommentResponse\x122\n" +
	"\acomment\x18\x01 \x01(\v2\x18.comment_service.CommentR\acomment\"]\n" +
	"\x0fGetLikesRequest\x12\x1c\n" +
	"\tcommentId\x18\x01 \x01(\tR\tcommentId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\x9f\x01\n" +
	"\vLikeComment\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x1f\n" +
	"\vtarget_type\x18\x03 \x01(\tR\n" +
	"targetType\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"F\n" +
	"\x10GetLikesResponse\x122\n" +
	"\x05likes\x18\x01 \x03(\v2\x1c.comment_service.LikeCommentR\x05likes2\xda\a\n" +
	"\x0eCommentService\x12U\n" +
	"\n" +
	"AddComment\x12\".comment_service.AddCommentRequest\x1a#.comment_service.AddCommentResponse\x12^\n" +
	"\rDeleteComment\x12%.comment_service.DeleteCommentRequest\x1a&.comment_service.DeleteCommentResponse\x12^\n" +
	"\rUpdateComment\x12%.comment_service.UpdateCommentRequest\x1a&.comment_service.UpdateCommentResponse\x12s\n" +
	"\x14FetchCommentsForPost\x12,.comment_service.FetchCommentsForPostRequest\x1a-.comment_service.FetchCommentsForPostResponse\x12X\n" +
	"\vLikeComment\x12#.comment_service.LikeCommentRequest\x1a$.comment_service.LikeCommentResponse\x12^\n" +
	"\rUnlikeComment\x12%.comment_service.UnlikeCommentRequest\x1a&.comment_service.UnlikeCommentResponse\x12U\n" +
	"\n" +
	"GetComment\x12\".comment_service.GetCommentRequest\x1a#.comment_service.GetCommentResponse\x12d\n" +
	"\x0fGetCommentFiles\x12'.comment_service.GetCommentFilesRequest\x1a(.comment_service.GetCommentFilesResponse\x12m\n" +
	"\x12GetLastPostComment\x12*.comment_service.GetLastPostCommentRequest\x1a+.comment_service.GetLastPostCommentResponse\x12V\n" +
	"\x0fGetCommentLikes\x12 .comment_service.GetLikesRequest\x1a!.comment_service.GetLikesResponseB8Z6quickflow/comment_service/internal/delivery/grpc/protob\x06proto3"

var (
	file_comment_service_proto_rawDescOnce sync.Once
	file_comment_service_proto_rawDescData []byte
)

func file_comment_service_proto_rawDescGZIP() []byte {
	file_comment_service_proto_rawDescOnce.Do(func() {
		file_comment_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comment_service_proto_rawDesc), len(file_comment_service_proto_rawDesc)))
	})
	return file_comment_service_proto_rawDescData
}

var file_comment_service_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_comment_service_proto_goTypes = []any{
	(*Comment)(nil),                      // 0: comment_service.Comment
	(*CommentUpdate)(nil),                // 1: comment_service.CommentUpdate
	(*AddCommentRequest)(nil),            // 2: comment_service.AddCommentRequest
	(*AddCommentResponse)(nil),           // 3: comment_service.AddCommentResponse
	(*DeleteCommentRequest)(nil),         // 4: comment_service.DeleteCommentRequest
	(*DeleteCommentResponse)(nil),        // 5: comment_service.DeleteCommentResponse
	(*UpdateCommentRequest)(nil),         // 6: comment_service.UpdateCommentRequest
	(*UpdateCommentResponse)(nil),        // 7: comment_service.UpdateCommentResponse
	(*FetchCommentsForPostRequest)(nil),  // 8: comment_service.FetchCommentsForPostRequest
	(*FetchCommentsForPostResponse)(nil), // 9: comment_service.FetchCommentsForPostResponse
	(*LikeCommentRequest)(nil),           // 10: comment_service.LikeCommentRequest
	(*LikeCommentResponse)(nil),          // 11: comment_service.LikeCommentResponse
	(*UnlikeCommentRequest)(nil),         // 12: comment_service.UnlikeCommentRequest
	(*UnlikeCommentResponse)(nil),        // 13: comment_service.UnlikeCommentResponse
	(*GetCommentRequest)(nil),            // 14: comment_service.GetCommentRequest
	(*GetCommentResponse)(nil),           // 15: comment_service.GetCommentResponse
	(*GetCommentFilesRequest)(nil),       // 16: comment_service.GetCommentFilesRequest
	(*GetCommentFilesResponse)(nil),      // 17: comment_service.GetCommentFilesResponse
	(*GetLastPostCommentRequest)(nil),    // 18: comment_service.GetLastPostCommentRequest
	(*GetLastPostCommentResponse)(nil),   // 19: comment_service.GetLastPostCommentResponse
	(*GetLikesRequest)(nil),              // 20: comment_service.GetLikesRequest
	(*LikeComment)(nil),                  // 21: comment_service.LikeComment
	(*GetLikesResponse)(nil),             // 22: comment_service.GetLikesResponse
	(*file_service.File)(nil),            // 23: file_service.File
	(*timestamppb.Timestamp)(nil),        // 24: google.protobuf.Timestamp
}
var file_comment_service_proto_depIdxs = []int32{
	23, // 0: comment_service.Comment.images:type_name -> file_service.File
	23, // 1: comment_service.CommentUpdate.files:type_name -> file_service.File
	0,  // 2: comment_service.AddCommentRequest.comment:type_name -> comment_service.Comment
	0,  // 3: comment_service.AddCommentResponse.comment:type_name -> comment_service.Comment
	1,  // 4: comment_service.UpdateCommentRequest.comment:type_name -> comment_service.CommentUpdate
	0,  // 5: comment_service.UpdateCommentResponse.comment:type_name -> comment_service.Comment
	0,  // 6: comment_service.FetchCommentsForPostResponse.comments:type_name -> comment_service.Comment
	0,  // 7: comment_service.GetCommentResponse.comment:type_name -> comment_service.Comment
	0,  // 8: comment_service.GetLastPostCommentResponse.comment:type_name -> comment_service.Comment
	24, // 9: comment_service.LikeComment.created_at:type_name -> google.protobuf.Timestamp
	21, // 10: comment_service.GetLikesResponse.likes:type_name -> comment_service.LikeComment
	2,  // 11: comment_service.CommentService.AddComment:input_type -> comment_service.AddCommentRequest
	4,  // 12: comment_service.CommentService.DeleteComment:input_type -> comment_service.DeleteCommentRequest
	6,  // 13: comment_service.CommentService.UpdateComment:input_type -> comment_service.UpdateCommentRequest
	8,  // 14: comment_service.CommentService.FetchCommentsForPost:input_type -> comment_service.FetchCommentsForPostRequest
	10, // 15: comment_service.CommentService.LikeComment:input_type -> comment_service.LikeCommentRequest
	12, // 16: comment_service.CommentService.UnlikeComment:input_type -> comment_service.UnlikeCommentRequest
	14, // 17: comment_service.CommentService.GetComment:input_type -> comment_service.GetCommentRequest
	16, // 18: comment_service.CommentService.GetCommentFiles:input_type -> comment_service.GetCommentFilesRequest
	18, // 19: comment_service.CommentService.GetLastPostComment:input_type -> comment_service.GetLastPostCommentRequest
	20, // 20: comment_service.CommentService.GetCommentLikes:input_type -> comment_service.GetLikesRequest
	3,  // 21: comment_service.CommentService.AddComment:output_type -> comment_service.AddCommentResponse
	5,  // 22: comment_service.CommentService.DeleteComment:output_type -> comment_service.DeleteCommentResponse
	7,  // 23: comment_service.CommentService.UpdateComment:output_type -> comment_service.UpdateCommentResponse
	9,  // 24: comment_service.CommentService.FetchCommentsForPost:output_type -> comment_service.FetchCommentsForPostResponse
	11, // 25: comment_service.CommentService.LikeComment:output_type -> comment_service.LikeCommentResponse
	13, // 26: comment_service.CommentService.UnlikeComment:output_type -> comment_service.UnlikeCommentResponse
	15, // 27: comment_service.CommentService.GetComment:output_type -> comment_service.GetCommentResponse
	17, // 28: comment_service.CommentService.GetCommentFiles:output_type -> comment_service.GetCommentFilesResponse
	19, // 29: comment_service.CommentService.GetLastPostComment:output_type -> comment_service.GetLastPostCommentResponse
	22, // 30: comment_service.CommentService.GetCommentLikes:output_type -> comment_service.GetLikesResponse
	21, // [21:31] is the sub-list for method output_type
	11, // [11:21] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_comment_service_proto_init() }
func file_comment_service_proto_init() {
	if File_comment_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comment_service_proto_rawDesc), len(file_comment_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comment_service_proto_goTypes,
		DependencyIndexes: file_comment_service_proto_depIdxs,
		MessageInfos:      file_comment_service_proto_msgTypes,
	}.Build()
	File_comment_service_proto = out.File
	file_comment_service_proto_goTypes = nil
	file_comment_service_proto_depIdxs = nil
}
