// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: post_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	file_service "quickflow/shared/proto/file_service"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId     string                 `protobuf:"bytes,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	CreatorType   string                 `protobuf:"bytes,12,opt,name=creator_type,json=creatorType,proto3" json:"creator_type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Files         []*file_service.File   `protobuf:"bytes,5,rep,name=files,proto3" json:"files,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LikeCount     int64                  `protobuf:"varint,8,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	RepostCount   int64                  `protobuf:"varint,9,opt,name=repost_count,json=repostCount,proto3" json:"repost_count,omitempty"`
	CommentCount  int64                  `protobuf:"varint,10,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	IsRepost      bool                   `protobuf:"varint,11,opt,name=is_repost,json=isRepost,proto3" json:"is_repost,omitempty"`
	IsLiked       bool                   `protobuf:"varint,13,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_post_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_post_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_post_service_proto_rawDescGZIP(), []int{0}
}

func (x *Post) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Post) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *Post) GetCreatorType() string {
	if x != nil {
		return x.CreatorType
	}
	return ""
}

func (x *Post) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Post) GetFiles() []*file_service.File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Post) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Post) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Post) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Post) GetRepostCount() int64 {
	if x != nil {
		return x.RepostCount
	}
	return 0
}

func (x *Post) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Post) GetIsRepost() bool {
	if x != nil {
		return x.IsRepost
	}
	return false
}

func (x *Post) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

type LikePost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetType    string                 `protobuf:"bytes,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikePost) Reset() {
	*x = LikePost{}
	mi := &file_post_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikePost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePost) ProtoMessage() {}

func (x *LikePost) ProtoReflect() protoreflect.Message {
	mi := &file_post_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePost.ProtoReflect.Descriptor instead.
func (*LikePost) Descriptor() ([]byte, []int) {
	return file_post_service_proto_rawDescGZIP(), []int{1}
}

func (x *LikePost) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LikePost) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *LikePost) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *LikePost) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type PostUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Files         []*file_service.File   `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostUpdate) Reset() {
	*x = PostUpdate{}
	mi := &file_post_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUpdate) ProtoMessage() {}

func (x *PostUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_post_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUpdate.ProtoReflect.Descriptor instead.
func (*PostUpdate) Descriptor() ([]byte, []int) {
	return file_post_service_proto_rawDescGZIP(), []int{2}
}

func (x *PostUpdate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PostUpdate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PostUpdate) GetFiles() []*file_service.File {
	if x != nil {
		return x.Files
	}
	return nil
}

type AddPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPostRequest) Reset() {
	*x = AddPostRequest{}
	mi := &file_post_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPostRequest) ProtoMessage() {}

func (x *AddPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPostRequest.ProtoReflect.Descriptor instead.
func (*AddPostRequest) Descriptor() ([]byte, []int) {
	return file_post_service_proto_rawDescGZIP(), []int{3}
}

func (x *AddPostRequest) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type AddPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPostResponse) Reset() {
	*x = AddPostResponse{}
	mi := &file_post_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPostResponse) ProtoMessage() {}

func (x *AddPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPostResponse.ProtoReflect.Descriptor instead.
func (*AddPostResponse) Descriptor() ([]byte, []int) {
	return file_post_service_proto_rawDescGZIP(), []int{4}
}

func (x *AddPostResponse) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type DeletePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	mi := &file_post_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_post_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *DeletePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeletePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostResponse) Reset() {
	*x = DeletePostResponse{}
	mi := &file_post_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostResponse) ProtoMessage() {}

func (x *DeletePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostResponse.ProtoReflect.Descriptor instead.
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return file_post_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type FetchFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumPosts      int32                  `protobuf:"varint,1,opt,name=num_posts,json=numPosts,proto3" json:"num_posts,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchFeedRequest) Reset() {
	*x = FetchFeedRequest{}
	mi := &file_post_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchFeedRequest) ProtoMessage() {}

func (x *FetchFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchFeedRequest.ProtoReflect.Descriptor instead.
func (*FetchFeedRequest) Descriptor() ([]byte, []int) {
	return file_post_service_proto_rawDescGZIP(), []int{7}
}

func (x *FetchFeedRequest) GetNumPosts() int32 {
	if x != nil {
		return x.NumPosts
	}
	return 0
}

func (x *FetchFeedRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *FetchFeedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FetchFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchFeedResponse) Reset() {
	*x = FetchFeedResponse{}
	mi := &file_post_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchFeedResponse) ProtoMessage() {}

func (x *FetchFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchFeedResponse.ProtoReflect.Descriptor instead.
func (*FetchFeedResponse) Descriptor() ([]byte, []int) {
	return file_post_service_proto_rawDescGZIP(), []int{8}
}

func (x *FetchFeedResponse) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

type FetchRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumPosts      int32                  `protobuf:"varint,1,opt,name=num_posts,json=numPosts,proto3" json:"num_posts,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRecommendationsRequest) Reset() {
	*x = FetchRecommendationsRequest{}
	mi := &file_post_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRecommendationsRequest) ProtoMessage() {}

func (x *FetchRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*FetchRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_post_service_proto_rawDescGZIP(), []int{9}
}

func (x *FetchRecommendationsRequest) GetNumPosts() int32 {
	if x != nil {
		return x.NumPosts
	}
	return 0
}

func (x *FetchRecommendationsRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *FetchRecommendationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FetchRecommendationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRecommendationsResponse) Reset() {
	*x = FetchRecommendationsResponse{}
	mi := &file_post_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRecommendationsResponse) ProtoMessage() {}

func (x *FetchRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*FetchRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_post_service_proto_rawDescGZIP(), []int{10}
}

func (x *FetchRecommendationsResponse) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

type FetchUserPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NumPosts      int32                  `protobuf:"varint,2,opt,name=num_posts,json=numPosts,proto3" json:"num_posts,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RequesterId   string                 `protobuf:"bytes,4,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchUserPostsRequest) Reset() {
	*x = FetchUserPostsRequest{}
	mi := &file_post_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchUserPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchUserPostsRequest) ProtoMessage() {}

func (x *FetchUserPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchUserPostsRequest.ProtoReflect.Descriptor instead.
func (*FetchUserPostsRequest) Descriptor() ([]byte, []int) {
	return file_post_service_proto_rawDescGZIP(), []int{11}
}

func (x *FetchUserPostsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FetchUserPostsRequest) GetNumPosts() int32 {
	if x != nil {
		return x.NumPosts
	}
	return 0
}

func (x *FetchUserPostsRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *FetchUserPostsRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type FetchUserPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchUserPostsResponse) Reset() {
	*x = FetchUserPostsResponse{}
	mi := &file_post_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchUserPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchUserPostsResponse) ProtoMessage() {}

func (x *FetchUserPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchUserPostsResponse.ProtoReflect.Descriptor instead.
func (*FetchUserPostsResponse) Descriptor() ([]byte, []int) {
	return file_post_service_proto_rawDescGZIP(), []int{12}
}

func (x *FetchUserPostsResponse) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

type UpdatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *PostUpdate            `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostRequest) Reset() {
	*x = UpdatePostRequest{}
	mi := &file_post_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostRequest) ProtoMessage() {}

func (x *UpdatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return file_post_service_proto_rawDescGZIP(), []int{13}
}

func (x *UpdatePostRequest) GetPost() *PostUpdate {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *UpdatePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostResponse) Reset() {
	*x = UpdatePostResponse{}
	mi := &file_post_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostResponse) ProtoMessage() {}

func (x *UpdatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostResponse.ProtoReflect.Descriptor instead.
func (*UpdatePostResponse) Descriptor() ([]byte, []int) {
	return file_post_service_proto_rawDescGZIP(), []int{14}
}

func (x *UpdatePostResponse) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type LikePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikePostRequest) Reset() {
	*x = LikePostRequest{}
	mi := &file_post_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePostRequest) ProtoMessage() {}

func (x *LikePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePostRequest.ProtoReflect.Descriptor instead.
func (*LikePostRequest) Descriptor() ([]byte, []int) {
	return file_post_service_proto_rawDescGZIP(), []int{15}
}

func (x *LikePostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *LikePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LikePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikePostResponse) Reset() {
	*x = LikePostResponse{}
	mi := &file_post_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePostResponse) ProtoMessage() {}

func (x *LikePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePostResponse.ProtoReflect.Descriptor instead.
func (*LikePostResponse) Descriptor() ([]byte, []int) {
	return file_post_service_proto_rawDescGZIP(), []int{16}
}

func (x *LikePostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnlikePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikePostRequest) Reset() {
	*x = UnlikePostRequest{}
	mi := &file_post_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikePostRequest) ProtoMessage() {}

func (x *UnlikePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikePostRequest.ProtoReflect.Descriptor instead.
func (*UnlikePostRequest) Descriptor() ([]byte, []int) {
	return file_post_service_proto_rawDescGZIP(), []int{17}
}

func (x *UnlikePostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *UnlikePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UnlikePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikePostResponse) Reset() {
	*x = UnlikePostResponse{}
	mi := &file_post_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikePostResponse) ProtoMessage() {}

func (x *UnlikePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikePostResponse.ProtoReflect.Descriptor instead.
func (*UnlikePostResponse) Descriptor() ([]byte, []int) {
	return file_post_service_proto_rawDescGZIP(), []int{18}
}

func (x *UnlikePostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_post_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_post_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *GetPostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostResponse) Reset() {
	*x = GetPostResponse{}
	mi := &file_post_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostResponse) ProtoMessage() {}

func (x *GetPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostResponse.ProtoReflect.Descriptor instead.
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return file_post_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetPostResponse) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type GetPostLikesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostLikesRequest) Reset() {
	*x = GetPostLikesRequest{}
	mi := &file_post_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostLikesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostLikesRequest) ProtoMessage() {}

func (x *GetPostLikesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostLikesRequest.ProtoReflect.Descriptor instead.
func (*GetPostLikesRequest) Descriptor() ([]byte, []int) {
	return file_post_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetPostLikesRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *GetPostLikesRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetPostLikesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetPostLikesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Likes         []*LikePost            `protobuf:"bytes,1,rep,name=likes,proto3" json:"likes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostLikesResponse) Reset() {
	*x = GetPostLikesResponse{}
	mi := &file_post_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostLikesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostLikesResponse) ProtoMessage() {}

func (x *GetPostLikesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostLikesResponse.ProtoReflect.Descriptor instead.
func (*GetPostLikesResponse) Descriptor() ([]byte, []int) {
	return file_post_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetPostLikesResponse) GetLikes() []*LikePost {
	if x != nil {
		return x.Likes
	}
	return nil
}

var File_post_service_proto protoreflect.FileDescriptor

const file_post_service_proto_rawDesc = "" +
	"\n" +
	"\x12post_service.proto\x12\fpost_service\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ffile_service/file_service.proto\"\xb9\x03\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\tR\tcreatorId\x12!\n" +
	"\fcreator_type\x18\f \x01(\tR\vcreatorType\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12(\n" +
	"\x05files\x18\x05 \x03(\v2\x12.file_service.FileR\x05files\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"like_count\x18\b \x01(\x03R\tlikeCount\x12!\n" +
	"\frepost_count\x18\t \x01(\x03R\vrepostCount\x12#\n" +
	"\rcomment_count\x18\n" +
	" \x01(\x03R\fcommentCount\x12\x1b\n" +
	"\tis_repost\x18\v \x01(\bR\bisRepost\x12\x19\n" +
	"\bis_liked\x18\r \x01(\bR\aisLiked\"\x9c\x01\n" +
	"\bLikePost\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x1f\n" +
	"\vtarget_type\x18\x03 \x01(\tR\n" +
	"targetType\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"h\n" +
	"\n" +
	"PostUpdate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12(\n" +
	"\x05files\x18\x03 \x03(\v2\x12.file_service.FileR\x05files\"8\n" +
	"\x0eAddPostRequest\x12&\n" +
	"\x04post\x18\x01 \x01(\v2\x12.post_service.PostR\x04post\"9\n" +
	"\x0fAddPostResponse\x12&\n" +
	"\x04post\x18\x01 \x01(\v2\x12.post_service.PostR\x04post\"E\n" +
	"\x11DeletePostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\".\n" +
	"\x12DeletePostResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x82\x01\n" +
	"\x10FetchFeedRequest\x12\x1b\n" +
	"\tnum_posts\x18\x01 \x01(\x05R\bnumPosts\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"=\n" +
	"\x11FetchFeedResponse\x12(\n" +
	"\x05posts\x18\x01 \x03(\v2\x12.post_service.PostR\x05posts\"\x8d\x01\n" +
	"\x1bFetchRecommendationsRequest\x12\x1b\n" +
	"\tnum_posts\x18\x01 \x01(\x05R\bnumPosts\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"H\n" +
	"\x1cFetchRecommendationsResponse\x12(\n" +
	"\x05posts\x18\x01 \x03(\v2\x12.post_service.PostR\x05posts\"\xaa\x01\n" +
	"\x15FetchUserPostsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tnum_posts\x18\x02 \x01(\x05R\bnumPosts\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12!\n" +
	"\frequester_id\x18\x04 \x01(\tR\vrequesterId\"B\n" +
	"\x16FetchUserPostsResponse\x12(\n" +
	"\x05posts\x18\x01 \x03(\v2\x12.post_service.PostR\x05posts\"Z\n" +
	"\x11UpdatePostRequest\x12,\n" +
	"\x04post\x18\x01 \x01(\v2\x18.post_service.PostUpdateR\x04post\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"<\n" +
	"\x12UpdatePostResponse\x12&\n" +
	"\x04post\x18\x01 \x01(\v2\x12.post_service.PostR\x04post\"C\n" +
	"\x0fLikePostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\",\n" +
	"\x10LikePostResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"E\n" +
	"\x11UnlikePostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\".\n" +
	"\x12UnlikePostResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"B\n" +
	"\x0eGetPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"9\n" +
	"\x0fGetPostResponse\x12&\n" +
	"\x04post\x18\x01 \x01(\v2\x12.post_service.PostR\x04post\"[\n" +
	"\x13GetPostLikesRequest\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\tR\x06postId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"D\n" +
	"\x14GetPostLikesResponse\x12,\n" +
	"\x05likes\x18\x01 \x03(\v2\x16.post_service.LikePostR\x05likes2\xcc\x06\n" +
	"\vPostService\x12F\n" +
	"\aAddPost\x12\x1c.post_service.AddPostRequest\x1a\x1d.post_service.AddPostResponse\x12O\n" +
	"\n" +
	"DeletePost\x12\x1f.post_service.DeletePostRequest\x1a .post_service.DeletePostResponse\x12L\n" +
	"\tFetchFeed\x12\x1e.post_service.FetchFeedRequest\x1a\x1f.post_service.FetchFeedResponse\x12m\n" +
	"\x14FetchRecommendations\x12).post_service.FetchRecommendationsRequest\x1a*.post_service.FetchRecommendationsResponse\x12[\n" +
	"\x0eFetchUserPosts\x12#.post_service.FetchUserPostsRequest\x1a$.post_service.FetchUserPostsResponse\x12O\n" +
	"\n" +
	"UpdatePost\x12\x1f.post_service.UpdatePostRequest\x1a .post_service.UpdatePostResponse\x12I\n" +
	"\bLikePost\x12\x1d.post_service.LikePostRequest\x1a\x1e.post_service.LikePostResponse\x12O\n" +
	"\n" +
	"UnlikePost\x12\x1f.post_service.UnlikePostRequest\x1a .post_service.UnlikePostResponse\x12F\n" +
	"\aGetPost\x12\x1c.post_service.GetPostRequest\x1a\x1d.post_service.GetPostResponse\x12U\n" +
	"\fGetPostLikes\x12!.post_service.GetPostLikesRequest\x1a\".post_service.GetPostLikesResponseB5Z3quickflow/post_service/internal/delivery/grpc/protob\x06proto3"

var (
	file_post_service_proto_rawDescOnce sync.Once
	file_post_service_proto_rawDescData []byte
)

func file_post_service_proto_rawDescGZIP() []byte {
	file_post_service_proto_rawDescOnce.Do(func() {
		file_post_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_post_service_proto_rawDesc), len(file_post_service_proto_rawDesc)))
	})
	return file_post_service_proto_rawDescData
}

var file_post_service_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_post_service_proto_goTypes = []any{
	(*Post)(nil),                         // 0: post_service.Post
	(*LikePost)(nil),                     // 1: post_service.LikePost
	(*PostUpdate)(nil),                   // 2: post_service.PostUpdate
	(*AddPostRequest)(nil),               // 3: post_service.AddPostRequest
	(*AddPostResponse)(nil),              // 4: post_service.AddPostResponse
	(*DeletePostRequest)(nil),            // 5: post_service.DeletePostRequest
	(*DeletePostResponse)(nil),           // 6: post_service.DeletePostResponse
	(*FetchFeedRequest)(nil),             // 7: post_service.FetchFeedRequest
	(*FetchFeedResponse)(nil),            // 8: post_service.FetchFeedResponse
	(*FetchRecommendationsRequest)(nil),  // 9: post_service.FetchRecommendationsRequest
	(*FetchRecommendationsResponse)(nil), // 10: post_service.FetchRecommendationsResponse
	(*FetchUserPostsRequest)(nil),        // 11: post_service.FetchUserPostsRequest
	(*FetchUserPostsResponse)(nil),       // 12: post_service.FetchUserPostsResponse
	(*UpdatePostRequest)(nil),            // 13: post_service.UpdatePostRequest
	(*UpdatePostResponse)(nil),           // 14: post_service.UpdatePostResponse
	(*LikePostRequest)(nil),              // 15: post_service.LikePostRequest
	(*LikePostResponse)(nil),             // 16: post_service.LikePostResponse
	(*UnlikePostRequest)(nil),            // 17: post_service.UnlikePostRequest
	(*UnlikePostResponse)(nil),           // 18: post_service.UnlikePostResponse
	(*GetPostRequest)(nil),               // 19: post_service.GetPostRequest
	(*GetPostResponse)(nil),              // 20: post_service.GetPostResponse
	(*GetPostLikesRequest)(nil),          // 21: post_service.GetPostLikesRequest
	(*GetPostLikesResponse)(nil),         // 22: post_service.GetPostLikesResponse
	(*file_service.File)(nil),            // 23: file_service.File
	(*timestamppb.Timestamp)(nil),        // 24: google.protobuf.Timestamp
}
var file_post_service_proto_depIdxs = []int32{
	23, // 0: post_service.Post.files:type_name -> file_service.File
	24, // 1: post_service.Post.created_at:type_name -> google.protobuf.Timestamp
	24, // 2: post_service.Post.updated_at:type_name -> google.protobuf.Timestamp
	24, // 3: post_service.LikePost.created_at:type_name -> google.protobuf.Timestamp
	23, // 4: post_service.PostUpdate.files:type_name -> file_service.File
	0,  // 5: post_service.AddPostRequest.post:type_name -> post_service.Post
	0,  // 6: post_service.AddPostResponse.post:type_name -> post_service.Post
	24, // 7: post_service.FetchFeedRequest.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 8: post_service.FetchFeedResponse.posts:type_name -> post_service.Post
	24, // 9: post_service.FetchRecommendationsRequest.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 10: post_service.FetchRecommendationsResponse.posts:type_name -> post_service.Post
	24, // 11: post_service.FetchUserPostsRequest.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 12: post_service.FetchUserPostsResponse.posts:type_name -> post_service.Post
	2,  // 13: post_service.UpdatePostRequest.post:type_name -> post_service.PostUpdate
	0,  // 14: post_service.UpdatePostResponse.post:type_name -> post_service.Post
	0,  // 15: post_service.GetPostResponse.post:type_name -> post_service.Post
	1,  // 16: post_service.GetPostLikesResponse.likes:type_name -> post_service.LikePost
	3,  // 17: post_service.PostService.AddPost:input_type -> post_service.AddPostRequest
	5,  // 18: post_service.PostService.DeletePost:input_type -> post_service.DeletePostRequest
	7,  // 19: post_service.PostService.FetchFeed:input_type -> post_service.FetchFeedRequest
	9,  // 20: post_service.PostService.FetchRecommendations:input_type -> post_service.FetchRecommendationsRequest
	11, // 21: post_service.PostService.FetchUserPosts:input_type -> post_service.FetchUserPostsRequest
	13, // 22: post_service.PostService.UpdatePost:input_type -> post_service.UpdatePostRequest
	15, // 23: post_service.PostService.LikePost:input_type -> post_service.LikePostRequest
	17, // 24: post_service.PostService.UnlikePost:input_type -> post_service.UnlikePostRequest
	19, // 25: post_service.PostService.GetPost:input_type -> post_service.GetPostRequest
	21, // 26: post_service.PostService.GetPostLikes:input_type -> post_service.GetPostLikesRequest
	4,  // 27: post_service.PostService.AddPost:output_type -> post_service.AddPostResponse
	6,  // 28: post_service.PostService.DeletePost:output_type -> post_service.DeletePostResponse
	8,  // 29: post_service.PostService.FetchFeed:output_type -> post_service.FetchFeedResponse
	10, // 30: post_service.PostService.FetchRecommendations:output_type -> post_service.FetchRecommendationsResponse
	12, // 31: post_service.PostService.FetchUserPosts:output_type -> post_service.FetchUserPostsResponse
	14, // 32: post_service.PostService.UpdatePost:output_type -> post_service.UpdatePostResponse
	16, // 33: post_service.PostService.LikePost:output_type -> post_service.LikePostResponse
	18, // 34: post_service.PostService.UnlikePost:output_type -> post_service.UnlikePostResponse
	20, // 35: post_service.PostService.GetPost:output_type -> post_service.GetPostResponse
	22, // 36: post_service.PostService.GetPostLikes:output_type -> post_service.GetPostLikesResponse
	27, // [27:37] is the sub-list for method output_type
	17, // [17:27] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_post_service_proto_init() }
func file_post_service_proto_init() {
	if File_post_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_service_proto_rawDesc), len(file_post_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_post_service_proto_goTypes,
		DependencyIndexes: file_post_service_proto_depIdxs,
		MessageInfos:      file_post_service_proto_msgTypes,
	}.Build()
	File_post_service_proto = out.File
	file_post_service_proto_goTypes = nil
	file_post_service_proto_depIdxs = nil
}
