apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Базовые ресурсы
resources:
- ../../base
- namespace.yaml

# Специфичные для development настройки
#namespace: quickflow-dev

# Патчи для development
patches:
- path: gateway-patch.yaml
- path: replicas-patch.yaml

# Генерация configmap для development
configMapGenerator:
- name: dev-config
  literals:
  - ENV=development
  - DEBUG=true