apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData: # Используем stringData для удобства
  # Данные для Postgres
  POSTGRES_PASSWORD: "SuperSecurePassword1"
  # Данные для Redis
  REDIS_PASS: "22848Amogus"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
type: Opaque
stringData:
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minio_super_secret_password"