// Code generated by MockGen. DO NOT EDIT.
// Source: ./gateway/internal/delivery/ws/interfaces/interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	json "encoding/json"
	forms "quickflow/gateway/internal/delivery/http/forms"
	interfaces "quickflow/gateway/internal/delivery/ws/interfaces"
	models "quickflow/shared/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	websocket "github.com/gorilla/websocket"
)

// MockIWebSocketManager is a mock of IWebSocketManager interface.
type MockIWebSocketManager struct {
	ctrl     *gomock.Controller
	recorder *MockIWebSocketManagerMockRecorder
}

// MockIWebSocketManagerMockRecorder is the mock recorder for MockIWebSocketManager.
type MockIWebSocketManagerMockRecorder struct {
	mock *MockIWebSocketManager
}

// NewMockIWebSocketManager creates a new mock instance.
func NewMockIWebSocketManager(ctrl *gomock.Controller) *MockIWebSocketManager {
	mock := &MockIWebSocketManager{ctrl: ctrl}
	mock.recorder = &MockIWebSocketManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWebSocketManager) EXPECT() *MockIWebSocketManagerMockRecorder {
	return m.recorder
}

// AddConnection mocks base method.
func (m *MockIWebSocketManager) AddConnection(userId uuid.UUID, conn *websocket.Conn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddConnection", userId, conn)
}

// AddConnection indicates an expected call of AddConnection.
func (mr *MockIWebSocketManagerMockRecorder) AddConnection(userId, conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddConnection", reflect.TypeOf((*MockIWebSocketManager)(nil).AddConnection), userId, conn)
}

// HandlePing mocks base method.
func (m *MockIWebSocketManager) HandlePing(conn *websocket.Conn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandlePing", conn)
}

// HandlePing indicates an expected call of HandlePing.
func (mr *MockIWebSocketManagerMockRecorder) HandlePing(conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandlePing", reflect.TypeOf((*MockIWebSocketManager)(nil).HandlePing), conn)
}

// IsConnected mocks base method.
func (m *MockIWebSocketManager) IsConnected(userId uuid.UUID) (*websocket.Conn, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConnected", userId)
	ret0, _ := ret[0].(*websocket.Conn)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// IsConnected indicates an expected call of IsConnected.
func (mr *MockIWebSocketManagerMockRecorder) IsConnected(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConnected", reflect.TypeOf((*MockIWebSocketManager)(nil).IsConnected), userId)
}

// RemoveAndCloseConnection mocks base method.
func (m *MockIWebSocketManager) RemoveAndCloseConnection(userId uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveAndCloseConnection", userId)
}

// RemoveAndCloseConnection indicates an expected call of RemoveAndCloseConnection.
func (mr *MockIWebSocketManagerMockRecorder) RemoveAndCloseConnection(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAndCloseConnection", reflect.TypeOf((*MockIWebSocketManager)(nil).RemoveAndCloseConnection), userId)
}

// SendMessageToChat mocks base method.
func (m *MockIWebSocketManager) SendMessageToChat(ctx context.Context, message models.Message, publicSenderInfo models.PublicUserInfo, chatParticipants []models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessageToChat", ctx, message, publicSenderInfo, chatParticipants)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessageToChat indicates an expected call of SendMessageToChat.
func (mr *MockIWebSocketManagerMockRecorder) SendMessageToChat(ctx, message, publicSenderInfo, chatParticipants interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageToChat", reflect.TypeOf((*MockIWebSocketManager)(nil).SendMessageToChat), ctx, message, publicSenderInfo, chatParticipants)
}

// SendMessageToUser mocks base method.
func (m *MockIWebSocketManager) SendMessageToUser(ctx context.Context, userId uuid.UUID, message forms.MessageOut) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessageToUser", ctx, userId, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessageToUser indicates an expected call of SendMessageToUser.
func (mr *MockIWebSocketManagerMockRecorder) SendMessageToUser(ctx, userId, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageToUser", reflect.TypeOf((*MockIWebSocketManager)(nil).SendMessageToUser), ctx, userId, message)
}

// MockIWebSocketConnectionManager is a mock of IWebSocketConnectionManager interface.
type MockIWebSocketConnectionManager struct {
	ctrl     *gomock.Controller
	recorder *MockIWebSocketConnectionManagerMockRecorder
}

// MockIWebSocketConnectionManagerMockRecorder is the mock recorder for MockIWebSocketConnectionManager.
type MockIWebSocketConnectionManagerMockRecorder struct {
	mock *MockIWebSocketConnectionManager
}

// NewMockIWebSocketConnectionManager creates a new mock instance.
func NewMockIWebSocketConnectionManager(ctrl *gomock.Controller) *MockIWebSocketConnectionManager {
	mock := &MockIWebSocketConnectionManager{ctrl: ctrl}
	mock.recorder = &MockIWebSocketConnectionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWebSocketConnectionManager) EXPECT() *MockIWebSocketConnectionManagerMockRecorder {
	return m.recorder
}

// AddConnection mocks base method.
func (m *MockIWebSocketConnectionManager) AddConnection(userId uuid.UUID, conn *websocket.Conn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddConnection", userId, conn)
}

// AddConnection indicates an expected call of AddConnection.
func (mr *MockIWebSocketConnectionManagerMockRecorder) AddConnection(userId, conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddConnection", reflect.TypeOf((*MockIWebSocketConnectionManager)(nil).AddConnection), userId, conn)
}

// IsConnected mocks base method.
func (m *MockIWebSocketConnectionManager) IsConnected(userId uuid.UUID) (*websocket.Conn, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConnected", userId)
	ret0, _ := ret[0].(*websocket.Conn)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// IsConnected indicates an expected call of IsConnected.
func (mr *MockIWebSocketConnectionManagerMockRecorder) IsConnected(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConnected", reflect.TypeOf((*MockIWebSocketConnectionManager)(nil).IsConnected), userId)
}

// RemoveAndCloseConnection mocks base method.
func (m *MockIWebSocketConnectionManager) RemoveAndCloseConnection(userId uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveAndCloseConnection", userId)
}

// RemoveAndCloseConnection indicates an expected call of RemoveAndCloseConnection.
func (mr *MockIWebSocketConnectionManagerMockRecorder) RemoveAndCloseConnection(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAndCloseConnection", reflect.TypeOf((*MockIWebSocketConnectionManager)(nil).RemoveAndCloseConnection), userId)
}

// MockIWebSocketRouter is a mock of IWebSocketRouter interface.
type MockIWebSocketRouter struct {
	ctrl     *gomock.Controller
	recorder *MockIWebSocketRouterMockRecorder
}

// MockIWebSocketRouterMockRecorder is the mock recorder for MockIWebSocketRouter.
type MockIWebSocketRouterMockRecorder struct {
	mock *MockIWebSocketRouter
}

// NewMockIWebSocketRouter creates a new mock instance.
func NewMockIWebSocketRouter(ctrl *gomock.Controller) *MockIWebSocketRouter {
	mock := &MockIWebSocketRouter{ctrl: ctrl}
	mock.recorder = &MockIWebSocketRouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWebSocketRouter) EXPECT() *MockIWebSocketRouterMockRecorder {
	return m.recorder
}

// RegisterHandler mocks base method.
func (m *MockIWebSocketRouter) RegisterHandler(command string, handler interfaces.CommandHandler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterHandler", command, handler)
}

// RegisterHandler indicates an expected call of RegisterHandler.
func (mr *MockIWebSocketRouterMockRecorder) RegisterHandler(command, handler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterHandler", reflect.TypeOf((*MockIWebSocketRouter)(nil).RegisterHandler), command, handler)
}

// Route mocks base method.
func (m *MockIWebSocketRouter) Route(ctx context.Context, command string, user models.User, payload json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Route", ctx, command, user, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Route indicates an expected call of Route.
func (mr *MockIWebSocketRouterMockRecorder) Route(ctx, command, user, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Route", reflect.TypeOf((*MockIWebSocketRouter)(nil).Route), ctx, command, user, payload)
}
