// Code generated by MockGen. DO NOT EDIT.
// Source: ./gateway/internal/delivery/http/post-handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "quickflow/shared/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockWSLikeHandler is a mock of WSLikeHandler interface.
type MockWSLikeHandler struct {
	ctrl     *gomock.Controller
	recorder *MockWSLikeHandlerMockRecorder
}

// MockWSLikeHandlerMockRecorder is the mock recorder for MockWSLikeHandler.
type MockWSLikeHandlerMockRecorder struct {
	mock *MockWSLikeHandler
}

// NewMockWSLikeHandler creates a new mock instance.
func NewMockWSLikeHandler(ctrl *gomock.Controller) *MockWSLikeHandler {
	mock := &MockWSLikeHandler{ctrl: ctrl}
	mock.recorder = &MockWSLikeHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWSLikeHandler) EXPECT() *MockWSLikeHandlerMockRecorder {
	return m.recorder
}

// NotifyCommentLiked mocks base method.
func (m *MockWSLikeHandler) NotifyCommentLiked(ctx context.Context, senderId, receiverId uuid.UUID, comment *models.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyCommentLiked", ctx, senderId, receiverId, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyCommentLiked indicates an expected call of NotifyCommentLiked.
func (mr *MockWSLikeHandlerMockRecorder) NotifyCommentLiked(ctx, senderId, receiverId, comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyCommentLiked", reflect.TypeOf((*MockWSLikeHandler)(nil).NotifyCommentLiked), ctx, senderId, receiverId, comment)
}

// NotifyPostCommented mocks base method.
func (m *MockWSLikeHandler) NotifyPostCommented(ctx context.Context, senderId, receiverId uuid.UUID, post *models.Post, comment *models.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyPostCommented", ctx, senderId, receiverId, post, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyPostCommented indicates an expected call of NotifyPostCommented.
func (mr *MockWSLikeHandlerMockRecorder) NotifyPostCommented(ctx, senderId, receiverId, post, comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyPostCommented", reflect.TypeOf((*MockWSLikeHandler)(nil).NotifyPostCommented), ctx, senderId, receiverId, post, comment)
}

// NotifyPostLiked mocks base method.
func (m *MockWSLikeHandler) NotifyPostLiked(ctx context.Context, senderId, receiverId uuid.UUID, post *models.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyPostLiked", ctx, senderId, receiverId, post)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyPostLiked indicates an expected call of NotifyPostLiked.
func (mr *MockWSLikeHandlerMockRecorder) NotifyPostLiked(ctx, senderId, receiverId, post interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyPostLiked", reflect.TypeOf((*MockWSLikeHandler)(nil).NotifyPostLiked), ctx, senderId, receiverId, post)
}
