{
 "title": "Logs: 6 Groups + Infra",
 "tags": [
  "logs",
  "grouped",
  "optimized"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Количество логов deploy, записанных в течение 1 минуты",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({project=~\"deploy\",service!=\"loki\",service!=\"grafana\"}[1m])",
     "legendFormat": "deploy:{{service}}"
    },
    {
     "expr": "count_over_time({project=~\"quickflow_ro1\",service!=\"loki\",service!=\"grafana\"}[1m])",
     "legendFormat": "deploy(ro1):{{service}}"
    },
    {
     "expr": "count_over_time({project=~\"quickflow_ro2\",service!=\"loki\",service!=\"grafana\"}[1m])",
     "legendFormat": "deploy(ro2):{{service}}"
    }
   ]
  },
  {
   "title": "Количество логов mirror, записанных в течение 1 минуты",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({project=~\"quickflow_mirror\",service!=\"loki\",service!=\"grafana\"}[1m])",
     "legendFormat": "mirror:{{service}}"
    },
    {
     "expr": "count_over_time({project=~\"quickflow_mirror-ro1\",service!=\"loki\",service!=\"grafana\"}[1m])",
     "legendFormat": "mirror(ro1):{{service}}"
    },
    {
     "expr": "count_over_time({project=~\"quickflow_mirror-ro2\",service!=\"loki\",service!=\"grafana\"}[1m])",
     "legendFormat": "mirror(ro2):{{service}}"
    }
   ]
  },
  {
   "title": "Количество INFO логов deploy, записанных в течение 1 минуты",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({project=~\"deploy\",service!=\"loki\",service!=\"grafana\"} |~ `(?i)\\[INFO\\].*`[1m])",
     "legendFormat": "deploy:{{service}}"
    },
    {
     "expr": "count_over_time({project=~\"quickflow_ro1\",service!=\"loki\",service!=\"grafana\"} |~ `(?i)\\[INFO\\].*`[1m])",
     "legendFormat": "deploy(ro1):{{service}}"
    },
    {
     "expr": "count_over_time({project=~\"quickflow_ro2\",service!=\"loki\",service!=\"grafana\"} |~ `(?i)\\[INFO\\].*`[1m])",
     "legendFormat": "deploy(ro2):{{service}}"
    }
   ]
  },
  {
   "title": "Количество INFO логов mirror, записанных в течение 1 минуты",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({project=~\"quickflow_mirror\",service!=\"loki\",service!=\"grafana\"} |~ `(?i)\\[INFO\\].*`[1m])",
     "legendFormat": "mirror:{{service}}"
    },
    {
     "expr": "count_over_time({project=~\"quickflow_mirror-ro1\",service!=\"loki\",service!=\"grafana\"} |~ `(?i)\\[INFO\\].*`[1m])",
     "legendFormat": "mirror(ro1):{{service}}"
    },
    {
     "expr": "count_over_time({project=~\"quickflow_mirror-ro2\",service!=\"loki\",service!=\"grafana\"} |~ `(?i)\\[INFO\\].*`[1m])",
     "legendFormat": "mirror(ro2):{{service}}"
    }
   ]
  },
  {
   "title": "Количество ERROR логов deploy, записанных в течение 1 минуты",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count_over_time({project=~\"deploy\",service!=\"loki\",service!=\"grafana\"} |~ `(?i)\\[ERROR\\].*`[1m])",
     "legendFormat": "deploy:{{service}}"
    },
    {
     "expr": "count_over_time({project=~\"quickflow_ro1\",service!=\"loki\",service!=\"grafana\"} |~ `(?i)\\[ERROR\\].*`[1m])",
     "legendFormat": "deploy(ro1):{{service}}"
    },
    {
     "expr": "count_over_time({project=~\"quickflow_ro2\",service!=\"loki\",service!=\"grafana\"} |~ `(?i)\\[ERROR\\].*`[1m])",
     "legendFormat": "deploy(ro2):{{service}}"
    }
   ]
  },
  {
   "title": "Количество ERROR логов mirror, записанных в течение 1 минуты",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "count_over_time({project=~\"quickflow_mirror\",service!=\"loki\",service!=\"grafana\"} |~ `(?i)\\[ERROR\\].*`[1m])",
     "legendFormat": "mirror:{{service}}"
    },
    {
     "expr": "count_over_time({project=~\"quickflow_mirror-ro1\",service!=\"loki\",service!=\"grafana\"} |~ `(?i)\\[ERROR\\].*`[1m])",
     "legendFormat": "mirror(ro1):{{service}}"
    },
    {
     "expr": "count_over_time({project=~\"quickflow_mirror-ro2\",service!=\"loki\",service!=\"grafana\"} |~ `(?i)\\[ERROR\\].*`[1m])",
     "legendFormat": "mirror(ro2):{{service}}"
    }
   ]
  },
  { "title": "Основные приложения", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "main — deploy",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{container=~\"^(gateway|file_service|post_service|user_service|messenger_service|friends_service|feedback_service|community_service)$\"} |= \"\""
    }
   ]
  },
  {
   "title": "main readonly-1",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{container=~\"^(gateway|file_service|post_service|user_service|messenger_service|friends_service|feedback_service|community_service)-ro1$\"} |= \"\""
    }
   ]
  },
  {
   "title": "main readonly-2",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{container=~\"^(gateway|file_service|post_service|user_service|messenger_service|friends_service|feedback_service|community_service)-ro2$\"} |= \"\""
    }
   ]
  },
  {
   "title": "mirror",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "{container=~\"^(gateway|file_service|post_service|user_service|messenger_service|friends_service|feedback_service|community_service)-mirror$\"} |= \"\""
    }
   ]
  },
  {
   "title": "mirror readonly-1",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "{container=~\"^(gateway|file_service|post_service|user_service|messenger_service|friends_service|feedback_service|community_service)-mirror-ro1$\"} |= \"\""
    }
   ]
  },
  {
   "title": "mirror readonly-2",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "{container=~\"^(gateway|file_service|post_service|user_service|messenger_service|friends_service|feedback_service|community_service)-mirror-ro2$\"} |= \"\""
    }
   ]
  },
  { "title": "Infra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "postgres",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "{container=\"postgres\"} |= \"\""
    }
   ]
  },
  {
   "title": "postgres-slave",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "{container=\"postgres-slave\"} |= \"\""
    }
   ]
  },
  {
   "title": "redis",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "{container=\"redis\"} |= \"\""
    }
   ]
  },
  {
   "title": "minio",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "{container=\"minio\"} |= \"\""
    }
   ]
  }
 ]
}