FROM golang:1.24 AS tester

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./friends_service ./friends_service
COPY ./shared ./shared
COPY ./utils ./utils
COPY ./config ./config
COPY ./metrics ./metrics

CMD ["go", "test", "./friends_service/..."]
