// Code generated by MockGen. DO NOT EDIT.
// Source: ./gateway/internal/delivery/http/interfaces/interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "quickflow/shared/models"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockAuthUseCase is a mock of AuthUseCase interface.
type MockAuthUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAuthUseCaseMockRecorder
}

// MockAuthUseCaseMockRecorder is the mock recorder for MockAuthUseCase.
type MockAuthUseCaseMockRecorder struct {
	mock *MockAuthUseCase
}

// NewMockAuthUseCase creates a new mock instance.
func NewMockAuthUseCase(ctrl *gomock.Controller) *MockAuthUseCase {
	mock := &MockAuthUseCase{ctrl: ctrl}
	mock.recorder = &MockAuthUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthUseCase) EXPECT() *MockAuthUseCaseMockRecorder {
	return m.recorder
}

// AuthUser mocks base method.
func (m *MockAuthUseCase) AuthUser(ctx context.Context, authData models.LoginData) (models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthUser", ctx, authData)
	ret0, _ := ret[0].(models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthUser indicates an expected call of AuthUser.
func (mr *MockAuthUseCaseMockRecorder) AuthUser(ctx, authData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthUser", reflect.TypeOf((*MockAuthUseCase)(nil).AuthUser), ctx, authData)
}

// CreateUser mocks base method.
func (m *MockAuthUseCase) CreateUser(ctx context.Context, user models.User, profile models.Profile) (uuid.UUID, models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user, profile)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(models.Session)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockAuthUseCaseMockRecorder) CreateUser(ctx, user, profile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockAuthUseCase)(nil).CreateUser), ctx, user, profile)
}

// DeleteUserSession mocks base method.
func (m *MockAuthUseCase) DeleteUserSession(ctx context.Context, session string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserSession indicates an expected call of DeleteUserSession.
func (mr *MockAuthUseCaseMockRecorder) DeleteUserSession(ctx, session interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserSession", reflect.TypeOf((*MockAuthUseCase)(nil).DeleteUserSession), ctx, session)
}

// GetUserByUsername mocks base method.
func (m *MockAuthUseCase) GetUserByUsername(ctx context.Context, username string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockAuthUseCaseMockRecorder) GetUserByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockAuthUseCase)(nil).GetUserByUsername), ctx, username)
}

// LookupUserSession mocks base method.
func (m *MockAuthUseCase) LookupUserSession(ctx context.Context, session models.Session) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupUserSession", ctx, session)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupUserSession indicates an expected call of LookupUserSession.
func (mr *MockAuthUseCaseMockRecorder) LookupUserSession(ctx, session interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupUserSession", reflect.TypeOf((*MockAuthUseCase)(nil).LookupUserSession), ctx, session)
}

// MockChatUseCase is a mock of ChatUseCase interface.
type MockChatUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockChatUseCaseMockRecorder
}

// MockChatUseCaseMockRecorder is the mock recorder for MockChatUseCase.
type MockChatUseCaseMockRecorder struct {
	mock *MockChatUseCase
}

// NewMockChatUseCase creates a new mock instance.
func NewMockChatUseCase(ctrl *gomock.Controller) *MockChatUseCase {
	mock := &MockChatUseCase{ctrl: ctrl}
	mock.recorder = &MockChatUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatUseCase) EXPECT() *MockChatUseCaseMockRecorder {
	return m.recorder
}

// DeleteChat mocks base method.
func (m *MockChatUseCase) DeleteChat(ctx context.Context, chatId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChat", ctx, chatId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockChatUseCaseMockRecorder) DeleteChat(ctx, chatId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockChatUseCase)(nil).DeleteChat), ctx, chatId)
}

// GetChat mocks base method.
func (m *MockChatUseCase) GetChat(ctx context.Context, chatId uuid.UUID) (*models.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChat", ctx, chatId)
	ret0, _ := ret[0].(*models.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChat indicates an expected call of GetChat.
func (mr *MockChatUseCaseMockRecorder) GetChat(ctx, chatId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChat", reflect.TypeOf((*MockChatUseCase)(nil).GetChat), ctx, chatId)
}

// GetChatParticipants mocks base method.
func (m *MockChatUseCase) GetChatParticipants(ctx context.Context, chatId uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatParticipants", ctx, chatId)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatParticipants indicates an expected call of GetChatParticipants.
func (mr *MockChatUseCaseMockRecorder) GetChatParticipants(ctx, chatId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatParticipants", reflect.TypeOf((*MockChatUseCase)(nil).GetChatParticipants), ctx, chatId)
}

// GetNumUnreadChats mocks base method.
func (m *MockChatUseCase) GetNumUnreadChats(ctx context.Context, userId uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNumUnreadChats", ctx, userId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNumUnreadChats indicates an expected call of GetNumUnreadChats.
func (mr *MockChatUseCaseMockRecorder) GetNumUnreadChats(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNumUnreadChats", reflect.TypeOf((*MockChatUseCase)(nil).GetNumUnreadChats), ctx, userId)
}

// GetPrivateChat mocks base method.
func (m *MockChatUseCase) GetPrivateChat(ctx context.Context, userId1, userId2 uuid.UUID) (*models.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivateChat", ctx, userId1, userId2)
	ret0, _ := ret[0].(*models.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrivateChat indicates an expected call of GetPrivateChat.
func (mr *MockChatUseCaseMockRecorder) GetPrivateChat(ctx, userId1, userId2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivateChat", reflect.TypeOf((*MockChatUseCase)(nil).GetPrivateChat), ctx, userId1, userId2)
}

// GetUserChats mocks base method.
func (m *MockChatUseCase) GetUserChats(ctx context.Context, userId uuid.UUID, numChats int, ts time.Time) ([]models.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserChats", ctx, userId, numChats, ts)
	ret0, _ := ret[0].([]models.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserChats indicates an expected call of GetUserChats.
func (mr *MockChatUseCaseMockRecorder) GetUserChats(ctx, userId, numChats, ts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserChats", reflect.TypeOf((*MockChatUseCase)(nil).GetUserChats), ctx, userId, numChats, ts)
}

// JoinChat mocks base method.
func (m *MockChatUseCase) JoinChat(ctx context.Context, chatId, userId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinChat", ctx, chatId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// JoinChat indicates an expected call of JoinChat.
func (mr *MockChatUseCaseMockRecorder) JoinChat(ctx, chatId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinChat", reflect.TypeOf((*MockChatUseCase)(nil).JoinChat), ctx, chatId, userId)
}

// LeaveChat mocks base method.
func (m *MockChatUseCase) LeaveChat(ctx context.Context, chatId, userId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeaveChat", ctx, chatId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// LeaveChat indicates an expected call of LeaveChat.
func (mr *MockChatUseCaseMockRecorder) LeaveChat(ctx, chatId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaveChat", reflect.TypeOf((*MockChatUseCase)(nil).LeaveChat), ctx, chatId, userId)
}

// MockCommentService is a mock of CommentService interface.
type MockCommentService struct {
	ctrl     *gomock.Controller
	recorder *MockCommentServiceMockRecorder
}

// MockCommentServiceMockRecorder is the mock recorder for MockCommentService.
type MockCommentServiceMockRecorder struct {
	mock *MockCommentService
}

// NewMockCommentService creates a new mock instance.
func NewMockCommentService(ctrl *gomock.Controller) *MockCommentService {
	mock := &MockCommentService{ctrl: ctrl}
	mock.recorder = &MockCommentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentService) EXPECT() *MockCommentServiceMockRecorder {
	return m.recorder
}

// AddComment mocks base method.
func (m *MockCommentService) AddComment(ctx context.Context, comment models.Comment) (*models.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddComment", ctx, comment)
	ret0, _ := ret[0].(*models.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddComment indicates an expected call of AddComment.
func (mr *MockCommentServiceMockRecorder) AddComment(ctx, comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddComment", reflect.TypeOf((*MockCommentService)(nil).AddComment), ctx, comment)
}

// DeleteComment mocks base method.
func (m *MockCommentService) DeleteComment(ctx context.Context, userId, commentId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComment", ctx, userId, commentId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockCommentServiceMockRecorder) DeleteComment(ctx, userId, commentId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockCommentService)(nil).DeleteComment), ctx, userId, commentId)
}

// FetchCommentsForPost mocks base method.
func (m *MockCommentService) FetchCommentsForPost(ctx context.Context, postId uuid.UUID, numComments int, timestamp time.Time) ([]models.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchCommentsForPost", ctx, postId, numComments, timestamp)
	ret0, _ := ret[0].([]models.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchCommentsForPost indicates an expected call of FetchCommentsForPost.
func (mr *MockCommentServiceMockRecorder) FetchCommentsForPost(ctx, postId, numComments, timestamp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchCommentsForPost", reflect.TypeOf((*MockCommentService)(nil).FetchCommentsForPost), ctx, postId, numComments, timestamp)
}

// GetComment mocks base method.
func (m *MockCommentService) GetComment(ctx context.Context, commentId, userId uuid.UUID) (*models.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComment", ctx, commentId, userId)
	ret0, _ := ret[0].(*models.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComment indicates an expected call of GetComment.
func (mr *MockCommentServiceMockRecorder) GetComment(ctx, commentId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComment", reflect.TypeOf((*MockCommentService)(nil).GetComment), ctx, commentId, userId)
}

// GetLastPostComment mocks base method.
func (m *MockCommentService) GetLastPostComment(ctx context.Context, postId uuid.UUID) (*models.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastPostComment", ctx, postId)
	ret0, _ := ret[0].(*models.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastPostComment indicates an expected call of GetLastPostComment.
func (mr *MockCommentServiceMockRecorder) GetLastPostComment(ctx, postId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastPostComment", reflect.TypeOf((*MockCommentService)(nil).GetLastPostComment), ctx, postId)
}

// LikeComment mocks base method.
func (m *MockCommentService) LikeComment(ctx context.Context, commentId, userId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LikeComment", ctx, commentId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// LikeComment indicates an expected call of LikeComment.
func (mr *MockCommentServiceMockRecorder) LikeComment(ctx, commentId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LikeComment", reflect.TypeOf((*MockCommentService)(nil).LikeComment), ctx, commentId, userId)
}

// UnlikeComment mocks base method.
func (m *MockCommentService) UnlikeComment(ctx context.Context, commentId, userId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlikeComment", ctx, commentId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlikeComment indicates an expected call of UnlikeComment.
func (mr *MockCommentServiceMockRecorder) UnlikeComment(ctx, commentId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlikeComment", reflect.TypeOf((*MockCommentService)(nil).UnlikeComment), ctx, commentId, userId)
}

// UpdateComment mocks base method.
func (m *MockCommentService) UpdateComment(ctx context.Context, update models.CommentUpdate, userId uuid.UUID) (*models.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateComment", ctx, update, userId)
	ret0, _ := ret[0].(*models.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateComment indicates an expected call of UpdateComment.
func (mr *MockCommentServiceMockRecorder) UpdateComment(ctx, update, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateComment", reflect.TypeOf((*MockCommentService)(nil).UpdateComment), ctx, update, userId)
}

// MockProfileUseCase is a mock of ProfileUseCase interface.
type MockProfileUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockProfileUseCaseMockRecorder
}

// MockProfileUseCaseMockRecorder is the mock recorder for MockProfileUseCase.
type MockProfileUseCaseMockRecorder struct {
	mock *MockProfileUseCase
}

// NewMockProfileUseCase creates a new mock instance.
func NewMockProfileUseCase(ctrl *gomock.Controller) *MockProfileUseCase {
	mock := &MockProfileUseCase{ctrl: ctrl}
	mock.recorder = &MockProfileUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileUseCase) EXPECT() *MockProfileUseCaseMockRecorder {
	return m.recorder
}

// GetProfileByUsername mocks base method.
func (m *MockProfileUseCase) GetProfileByUsername(ctx context.Context, username string) (models.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileByUsername", ctx, username)
	ret0, _ := ret[0].(models.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileByUsername indicates an expected call of GetProfileByUsername.
func (mr *MockProfileUseCaseMockRecorder) GetProfileByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileByUsername", reflect.TypeOf((*MockProfileUseCase)(nil).GetProfileByUsername), ctx, username)
}

// GetPublicUserInfo mocks base method.
func (m *MockProfileUseCase) GetPublicUserInfo(ctx context.Context, userId uuid.UUID) (models.PublicUserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicUserInfo", ctx, userId)
	ret0, _ := ret[0].(models.PublicUserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicUserInfo indicates an expected call of GetPublicUserInfo.
func (mr *MockProfileUseCaseMockRecorder) GetPublicUserInfo(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicUserInfo", reflect.TypeOf((*MockProfileUseCase)(nil).GetPublicUserInfo), ctx, userId)
}

// GetPublicUsersInfo mocks base method.
func (m *MockProfileUseCase) GetPublicUsersInfo(ctx context.Context, userIds []uuid.UUID) ([]models.PublicUserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicUsersInfo", ctx, userIds)
	ret0, _ := ret[0].([]models.PublicUserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicUsersInfo indicates an expected call of GetPublicUsersInfo.
func (mr *MockProfileUseCaseMockRecorder) GetPublicUsersInfo(ctx, userIds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicUsersInfo", reflect.TypeOf((*MockProfileUseCase)(nil).GetPublicUsersInfo), ctx, userIds)
}

// UpdateLastSeen mocks base method.
func (m *MockProfileUseCase) UpdateLastSeen(ctx context.Context, userId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastSeen", ctx, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastSeen indicates an expected call of UpdateLastSeen.
func (mr *MockProfileUseCaseMockRecorder) UpdateLastSeen(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastSeen", reflect.TypeOf((*MockProfileUseCase)(nil).UpdateLastSeen), ctx, userId)
}

// UpdateProfile mocks base method.
func (m *MockProfileUseCase) UpdateProfile(ctx context.Context, newProfile models.Profile) (*models.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, newProfile)
	ret0, _ := ret[0].(*models.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockProfileUseCaseMockRecorder) UpdateProfile(ctx, newProfile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockProfileUseCase)(nil).UpdateProfile), ctx, newProfile)
}

// MockCommunityService is a mock of CommunityService interface.
type MockCommunityService struct {
	ctrl     *gomock.Controller
	recorder *MockCommunityServiceMockRecorder
}

// MockCommunityServiceMockRecorder is the mock recorder for MockCommunityService.
type MockCommunityServiceMockRecorder struct {
	mock *MockCommunityService
}

// NewMockCommunityService creates a new mock instance.
func NewMockCommunityService(ctrl *gomock.Controller) *MockCommunityService {
	mock := &MockCommunityService{ctrl: ctrl}
	mock.recorder = &MockCommunityServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommunityService) EXPECT() *MockCommunityServiceMockRecorder {
	return m.recorder
}

// ChangeUserRole mocks base method.
func (m *MockCommunityService) ChangeUserRole(ctx context.Context, userId, communityId uuid.UUID, role models.CommunityRole, requester uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeUserRole", ctx, userId, communityId, role, requester)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeUserRole indicates an expected call of ChangeUserRole.
func (mr *MockCommunityServiceMockRecorder) ChangeUserRole(ctx, userId, communityId, role, requester interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeUserRole", reflect.TypeOf((*MockCommunityService)(nil).ChangeUserRole), ctx, userId, communityId, role, requester)
}

// CreateCommunity mocks base method.
func (m *MockCommunityService) CreateCommunity(ctx context.Context, community *models.Community) (*models.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCommunity", ctx, community)
	ret0, _ := ret[0].(*models.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCommunity indicates an expected call of CreateCommunity.
func (mr *MockCommunityServiceMockRecorder) CreateCommunity(ctx, community interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCommunity", reflect.TypeOf((*MockCommunityService)(nil).CreateCommunity), ctx, community)
}

// DeleteCommunity mocks base method.
func (m *MockCommunityService) DeleteCommunity(ctx context.Context, communityId, userId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCommunity", ctx, communityId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCommunity indicates an expected call of DeleteCommunity.
func (mr *MockCommunityServiceMockRecorder) DeleteCommunity(ctx, communityId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCommunity", reflect.TypeOf((*MockCommunityService)(nil).DeleteCommunity), ctx, communityId, userId)
}

// GetCommunityById mocks base method.
func (m *MockCommunityService) GetCommunityById(ctx context.Context, id uuid.UUID) (*models.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommunityById", ctx, id)
	ret0, _ := ret[0].(*models.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommunityById indicates an expected call of GetCommunityById.
func (mr *MockCommunityServiceMockRecorder) GetCommunityById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommunityById", reflect.TypeOf((*MockCommunityService)(nil).GetCommunityById), ctx, id)
}

// GetCommunityByName mocks base method.
func (m *MockCommunityService) GetCommunityByName(ctx context.Context, name string) (*models.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommunityByName", ctx, name)
	ret0, _ := ret[0].(*models.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommunityByName indicates an expected call of GetCommunityByName.
func (mr *MockCommunityServiceMockRecorder) GetCommunityByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommunityByName", reflect.TypeOf((*MockCommunityService)(nil).GetCommunityByName), ctx, name)
}

// GetCommunityMembers mocks base method.
func (m *MockCommunityService) GetCommunityMembers(ctx context.Context, communityId uuid.UUID, count int, ts time.Time) ([]*models.CommunityMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommunityMembers", ctx, communityId, count, ts)
	ret0, _ := ret[0].([]*models.CommunityMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommunityMembers indicates an expected call of GetCommunityMembers.
func (mr *MockCommunityServiceMockRecorder) GetCommunityMembers(ctx, communityId, count, ts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommunityMembers", reflect.TypeOf((*MockCommunityService)(nil).GetCommunityMembers), ctx, communityId, count, ts)
}

// GetControlledCommunities mocks base method.
func (m *MockCommunityService) GetControlledCommunities(ctx context.Context, userId uuid.UUID, count int, ts time.Time) ([]*models.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetControlledCommunities", ctx, userId, count, ts)
	ret0, _ := ret[0].([]*models.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetControlledCommunities indicates an expected call of GetControlledCommunities.
func (mr *MockCommunityServiceMockRecorder) GetControlledCommunities(ctx, userId, count, ts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetControlledCommunities", reflect.TypeOf((*MockCommunityService)(nil).GetControlledCommunities), ctx, userId, count, ts)
}

// GetUserCommunities mocks base method.
func (m *MockCommunityService) GetUserCommunities(ctx context.Context, userId uuid.UUID, count int, ts time.Time) ([]*models.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCommunities", ctx, userId, count, ts)
	ret0, _ := ret[0].([]*models.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCommunities indicates an expected call of GetUserCommunities.
func (mr *MockCommunityServiceMockRecorder) GetUserCommunities(ctx, userId, count, ts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCommunities", reflect.TypeOf((*MockCommunityService)(nil).GetUserCommunities), ctx, userId, count, ts)
}

// IsCommunityMember mocks base method.
func (m *MockCommunityService) IsCommunityMember(ctx context.Context, userId, communityId uuid.UUID) (bool, *models.CommunityRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCommunityMember", ctx, userId, communityId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*models.CommunityRole)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IsCommunityMember indicates an expected call of IsCommunityMember.
func (mr *MockCommunityServiceMockRecorder) IsCommunityMember(ctx, userId, communityId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCommunityMember", reflect.TypeOf((*MockCommunityService)(nil).IsCommunityMember), ctx, userId, communityId)
}

// JoinCommunity mocks base method.
func (m *MockCommunityService) JoinCommunity(ctx context.Context, member *models.CommunityMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinCommunity", ctx, member)
	ret0, _ := ret[0].(error)
	return ret0
}

// JoinCommunity indicates an expected call of JoinCommunity.
func (mr *MockCommunityServiceMockRecorder) JoinCommunity(ctx, member interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinCommunity", reflect.TypeOf((*MockCommunityService)(nil).JoinCommunity), ctx, member)
}

// LeaveCommunity mocks base method.
func (m *MockCommunityService) LeaveCommunity(ctx context.Context, userId, communityId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeaveCommunity", ctx, userId, communityId)
	ret0, _ := ret[0].(error)
	return ret0
}

// LeaveCommunity indicates an expected call of LeaveCommunity.
func (mr *MockCommunityServiceMockRecorder) LeaveCommunity(ctx, userId, communityId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaveCommunity", reflect.TypeOf((*MockCommunityService)(nil).LeaveCommunity), ctx, userId, communityId)
}

// SearchSimilarCommunities mocks base method.
func (m *MockCommunityService) SearchSimilarCommunities(ctx context.Context, name string, count int) ([]*models.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchSimilarCommunities", ctx, name, count)
	ret0, _ := ret[0].([]*models.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchSimilarCommunities indicates an expected call of SearchSimilarCommunities.
func (mr *MockCommunityServiceMockRecorder) SearchSimilarCommunities(ctx, name, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchSimilarCommunities", reflect.TypeOf((*MockCommunityService)(nil).SearchSimilarCommunities), ctx, name, count)
}

// UpdateCommunity mocks base method.
func (m *MockCommunityService) UpdateCommunity(ctx context.Context, community *models.Community, userId uuid.UUID) (*models.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCommunity", ctx, community, userId)
	ret0, _ := ret[0].(*models.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCommunity indicates an expected call of UpdateCommunity.
func (mr *MockCommunityServiceMockRecorder) UpdateCommunity(ctx, community, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCommunity", reflect.TypeOf((*MockCommunityService)(nil).UpdateCommunity), ctx, community, userId)
}

// MockPostService is a mock of PostService interface.
type MockPostService struct {
	ctrl     *gomock.Controller
	recorder *MockPostServiceMockRecorder
}

// MockPostServiceMockRecorder is the mock recorder for MockPostService.
type MockPostServiceMockRecorder struct {
	mock *MockPostService
}

// NewMockPostService creates a new mock instance.
func NewMockPostService(ctrl *gomock.Controller) *MockPostService {
	mock := &MockPostService{ctrl: ctrl}
	mock.recorder = &MockPostServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostService) EXPECT() *MockPostServiceMockRecorder {
	return m.recorder
}

// AddPost mocks base method.
func (m *MockPostService) AddPost(ctx context.Context, post models.Post) (*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPost", ctx, post)
	ret0, _ := ret[0].(*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPost indicates an expected call of AddPost.
func (mr *MockPostServiceMockRecorder) AddPost(ctx, post interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPost", reflect.TypeOf((*MockPostService)(nil).AddPost), ctx, post)
}

// DeletePost mocks base method.
func (m *MockPostService) DeletePost(ctx context.Context, userId, postId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePost", ctx, userId, postId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePost indicates an expected call of DeletePost.
func (mr *MockPostServiceMockRecorder) DeletePost(ctx, userId, postId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePost", reflect.TypeOf((*MockPostService)(nil).DeletePost), ctx, userId, postId)
}

// FetchCreatorPosts mocks base method.
func (m *MockPostService) FetchCreatorPosts(ctx context.Context, creatorId, requesterId uuid.UUID, numPosts int, timestamp time.Time) ([]models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchCreatorPosts", ctx, creatorId, requesterId, numPosts, timestamp)
	ret0, _ := ret[0].([]models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchCreatorPosts indicates an expected call of FetchCreatorPosts.
func (mr *MockPostServiceMockRecorder) FetchCreatorPosts(ctx, creatorId, requesterId, numPosts, timestamp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchCreatorPosts", reflect.TypeOf((*MockPostService)(nil).FetchCreatorPosts), ctx, creatorId, requesterId, numPosts, timestamp)
}

// FetchFeed mocks base method.
func (m *MockPostService) FetchFeed(ctx context.Context, numPosts int, timestamp time.Time, userId uuid.UUID) ([]models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchFeed", ctx, numPosts, timestamp, userId)
	ret0, _ := ret[0].([]models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchFeed indicates an expected call of FetchFeed.
func (mr *MockPostServiceMockRecorder) FetchFeed(ctx, numPosts, timestamp, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFeed", reflect.TypeOf((*MockPostService)(nil).FetchFeed), ctx, numPosts, timestamp, userId)
}

// FetchRecommendations mocks base method.
func (m *MockPostService) FetchRecommendations(ctx context.Context, numPosts int, timestamp time.Time, userId uuid.UUID) ([]models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchRecommendations", ctx, numPosts, timestamp, userId)
	ret0, _ := ret[0].([]models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchRecommendations indicates an expected call of FetchRecommendations.
func (mr *MockPostServiceMockRecorder) FetchRecommendations(ctx, numPosts, timestamp, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRecommendations", reflect.TypeOf((*MockPostService)(nil).FetchRecommendations), ctx, numPosts, timestamp, userId)
}

// GetPost mocks base method.
func (m *MockPostService) GetPost(ctx context.Context, postId, userId uuid.UUID) (*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPost", ctx, postId, userId)
	ret0, _ := ret[0].(*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPost indicates an expected call of GetPost.
func (mr *MockPostServiceMockRecorder) GetPost(ctx, postId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPost", reflect.TypeOf((*MockPostService)(nil).GetPost), ctx, postId, userId)
}

// LikePost mocks base method.
func (m *MockPostService) LikePost(ctx context.Context, postId, userId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LikePost", ctx, postId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// LikePost indicates an expected call of LikePost.
func (mr *MockPostServiceMockRecorder) LikePost(ctx, postId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LikePost", reflect.TypeOf((*MockPostService)(nil).LikePost), ctx, postId, userId)
}

// UnlikePost mocks base method.
func (m *MockPostService) UnlikePost(ctx context.Context, postId, userId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlikePost", ctx, postId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlikePost indicates an expected call of UnlikePost.
func (mr *MockPostServiceMockRecorder) UnlikePost(ctx, postId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlikePost", reflect.TypeOf((*MockPostService)(nil).UnlikePost), ctx, postId, userId)
}

// UpdatePost mocks base method.
func (m *MockPostService) UpdatePost(ctx context.Context, update models.PostUpdate, userId uuid.UUID) (*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePost", ctx, update, userId)
	ret0, _ := ret[0].(*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePost indicates an expected call of UpdatePost.
func (mr *MockPostServiceMockRecorder) UpdatePost(ctx, update, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePost", reflect.TypeOf((*MockPostService)(nil).UpdatePost), ctx, update, userId)
}

// MockFeedbackUseCase is a mock of FeedbackUseCase interface.
type MockFeedbackUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockFeedbackUseCaseMockRecorder
}

// MockFeedbackUseCaseMockRecorder is the mock recorder for MockFeedbackUseCase.
type MockFeedbackUseCaseMockRecorder struct {
	mock *MockFeedbackUseCase
}

// NewMockFeedbackUseCase creates a new mock instance.
func NewMockFeedbackUseCase(ctrl *gomock.Controller) *MockFeedbackUseCase {
	mock := &MockFeedbackUseCase{ctrl: ctrl}
	mock.recorder = &MockFeedbackUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedbackUseCase) EXPECT() *MockFeedbackUseCaseMockRecorder {
	return m.recorder
}

// GetAllFeedbackType mocks base method.
func (m *MockFeedbackUseCase) GetAllFeedbackType(ctx context.Context, feedbackType models.FeedbackType, ts time.Time, count int) ([]models.Feedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllFeedbackType", ctx, feedbackType, ts, count)
	ret0, _ := ret[0].([]models.Feedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllFeedbackType indicates an expected call of GetAllFeedbackType.
func (mr *MockFeedbackUseCaseMockRecorder) GetAllFeedbackType(ctx, feedbackType, ts, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllFeedbackType", reflect.TypeOf((*MockFeedbackUseCase)(nil).GetAllFeedbackType), ctx, feedbackType, ts, count)
}

// SaveFeedback mocks base method.
func (m *MockFeedbackUseCase) SaveFeedback(ctx context.Context, feedback *models.Feedback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFeedback", ctx, feedback)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFeedback indicates an expected call of SaveFeedback.
func (mr *MockFeedbackUseCaseMockRecorder) SaveFeedback(ctx, feedback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFeedback", reflect.TypeOf((*MockFeedbackUseCase)(nil).SaveFeedback), ctx, feedback)
}

// MockFileService is a mock of FileService interface.
type MockFileService struct {
	ctrl     *gomock.Controller
	recorder *MockFileServiceMockRecorder
}

// MockFileServiceMockRecorder is the mock recorder for MockFileService.
type MockFileServiceMockRecorder struct {
	mock *MockFileService
}

// NewMockFileService creates a new mock instance.
func NewMockFileService(ctrl *gomock.Controller) *MockFileService {
	mock := &MockFileService{ctrl: ctrl}
	mock.recorder = &MockFileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileService) EXPECT() *MockFileServiceMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockFileService) DeleteFile(ctx context.Context, filename string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, filename)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockFileServiceMockRecorder) DeleteFile(ctx, filename interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockFileService)(nil).DeleteFile), ctx, filename)
}

// UploadManyFiles mocks base method.
func (m *MockFileService) UploadManyFiles(ctx context.Context, files []*models.File) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadManyFiles", ctx, files)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadManyFiles indicates an expected call of UploadManyFiles.
func (mr *MockFileServiceMockRecorder) UploadManyFiles(ctx, files interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadManyFiles", reflect.TypeOf((*MockFileService)(nil).UploadManyFiles), ctx, files)
}

// MockFriendsUseCase is a mock of FriendsUseCase interface.
type MockFriendsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockFriendsUseCaseMockRecorder
}

// MockFriendsUseCaseMockRecorder is the mock recorder for MockFriendsUseCase.
type MockFriendsUseCaseMockRecorder struct {
	mock *MockFriendsUseCase
}

// NewMockFriendsUseCase creates a new mock instance.
func NewMockFriendsUseCase(ctrl *gomock.Controller) *MockFriendsUseCase {
	mock := &MockFriendsUseCase{ctrl: ctrl}
	mock.recorder = &MockFriendsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFriendsUseCase) EXPECT() *MockFriendsUseCaseMockRecorder {
	return m.recorder
}

// AcceptFriendRequest mocks base method.
func (m *MockFriendsUseCase) AcceptFriendRequest(ctx context.Context, senderID, receiverID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptFriendRequest", ctx, senderID, receiverID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptFriendRequest indicates an expected call of AcceptFriendRequest.
func (mr *MockFriendsUseCaseMockRecorder) AcceptFriendRequest(ctx, senderID, receiverID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptFriendRequest", reflect.TypeOf((*MockFriendsUseCase)(nil).AcceptFriendRequest), ctx, senderID, receiverID)
}

// DeleteFriend mocks base method.
func (m *MockFriendsUseCase) DeleteFriend(ctx context.Context, user, friend string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFriend", ctx, user, friend)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFriend indicates an expected call of DeleteFriend.
func (mr *MockFriendsUseCaseMockRecorder) DeleteFriend(ctx, user, friend interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFriend", reflect.TypeOf((*MockFriendsUseCase)(nil).DeleteFriend), ctx, user, friend)
}

// GetFriendsInfo mocks base method.
func (m *MockFriendsUseCase) GetFriendsInfo(ctx context.Context, userID, limit, offset, reqType string) ([]models.FriendInfo, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriendsInfo", ctx, userID, limit, offset, reqType)
	ret0, _ := ret[0].([]models.FriendInfo)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFriendsInfo indicates an expected call of GetFriendsInfo.
func (mr *MockFriendsUseCaseMockRecorder) GetFriendsInfo(ctx, userID, limit, offset, reqType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendsInfo", reflect.TypeOf((*MockFriendsUseCase)(nil).GetFriendsInfo), ctx, userID, limit, offset, reqType)
}

// GetUserRelation mocks base method.
func (m *MockFriendsUseCase) GetUserRelation(ctx context.Context, user1, user2 uuid.UUID) (models.UserRelation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRelation", ctx, user1, user2)
	ret0, _ := ret[0].(models.UserRelation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRelation indicates an expected call of GetUserRelation.
func (mr *MockFriendsUseCaseMockRecorder) GetUserRelation(ctx, user1, user2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRelation", reflect.TypeOf((*MockFriendsUseCase)(nil).GetUserRelation), ctx, user1, user2)
}

// MarkRead mocks base method.
func (m *MockFriendsUseCase) MarkRead(ctx context.Context, userID, friendID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRead", ctx, userID, friendID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkRead indicates an expected call of MarkRead.
func (mr *MockFriendsUseCaseMockRecorder) MarkRead(ctx, userID, friendID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRead", reflect.TypeOf((*MockFriendsUseCase)(nil).MarkRead), ctx, userID, friendID)
}

// SendFriendRequest mocks base method.
func (m *MockFriendsUseCase) SendFriendRequest(ctx context.Context, senderID, receiverID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendFriendRequest", ctx, senderID, receiverID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendFriendRequest indicates an expected call of SendFriendRequest.
func (mr *MockFriendsUseCaseMockRecorder) SendFriendRequest(ctx, senderID, receiverID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFriendRequest", reflect.TypeOf((*MockFriendsUseCase)(nil).SendFriendRequest), ctx, senderID, receiverID)
}

// Unfollow mocks base method.
func (m *MockFriendsUseCase) Unfollow(ctx context.Context, userID, friendID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unfollow", ctx, userID, friendID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unfollow indicates an expected call of Unfollow.
func (mr *MockFriendsUseCaseMockRecorder) Unfollow(ctx, userID, friendID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unfollow", reflect.TypeOf((*MockFriendsUseCase)(nil).Unfollow), ctx, userID, friendID)
}

// MockIFriendsWSManager is a mock of IFriendsWSManager interface.
type MockIFriendsWSManager struct {
	ctrl     *gomock.Controller
	recorder *MockIFriendsWSManagerMockRecorder
}

// MockIFriendsWSManagerMockRecorder is the mock recorder for MockIFriendsWSManager.
type MockIFriendsWSManagerMockRecorder struct {
	mock *MockIFriendsWSManager
}

// NewMockIFriendsWSManager creates a new mock instance.
func NewMockIFriendsWSManager(ctrl *gomock.Controller) *MockIFriendsWSManager {
	mock := &MockIFriendsWSManager{ctrl: ctrl}
	mock.recorder = &MockIFriendsWSManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFriendsWSManager) EXPECT() *MockIFriendsWSManagerMockRecorder {
	return m.recorder
}

// NotifyFriendRequestAccepted mocks base method.
func (m *MockIFriendsWSManager) NotifyFriendRequestAccepted(ctx context.Context, senderId, receiverId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyFriendRequestAccepted", ctx, senderId, receiverId)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyFriendRequestAccepted indicates an expected call of NotifyFriendRequestAccepted.
func (mr *MockIFriendsWSManagerMockRecorder) NotifyFriendRequestAccepted(ctx, senderId, receiverId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyFriendRequestAccepted", reflect.TypeOf((*MockIFriendsWSManager)(nil).NotifyFriendRequestAccepted), ctx, senderId, receiverId)
}

// NotifyFriendRequestSent mocks base method.
func (m *MockIFriendsWSManager) NotifyFriendRequestSent(ctx context.Context, senderId, receiverId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyFriendRequestSent", ctx, senderId, receiverId)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyFriendRequestSent indicates an expected call of NotifyFriendRequestSent.
func (mr *MockIFriendsWSManagerMockRecorder) NotifyFriendRequestSent(ctx, senderId, receiverId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyFriendRequestSent", reflect.TypeOf((*MockIFriendsWSManager)(nil).NotifyFriendRequestSent), ctx, senderId, receiverId)
}

// MockWSLikeHandler is a mock of WSLikeHandler interface.
type MockWSLikeHandler struct {
	ctrl     *gomock.Controller
	recorder *MockWSLikeHandlerMockRecorder
}

// MockWSLikeHandlerMockRecorder is the mock recorder for MockWSLikeHandler.
type MockWSLikeHandlerMockRecorder struct {
	mock *MockWSLikeHandler
}

// NewMockWSLikeHandler creates a new mock instance.
func NewMockWSLikeHandler(ctrl *gomock.Controller) *MockWSLikeHandler {
	mock := &MockWSLikeHandler{ctrl: ctrl}
	mock.recorder = &MockWSLikeHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWSLikeHandler) EXPECT() *MockWSLikeHandlerMockRecorder {
	return m.recorder
}

// NotifyCommentLiked mocks base method.
func (m *MockWSLikeHandler) NotifyCommentLiked(ctx context.Context, senderId, receiverId uuid.UUID, comment *models.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyCommentLiked", ctx, senderId, receiverId, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyCommentLiked indicates an expected call of NotifyCommentLiked.
func (mr *MockWSLikeHandlerMockRecorder) NotifyCommentLiked(ctx, senderId, receiverId, comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyCommentLiked", reflect.TypeOf((*MockWSLikeHandler)(nil).NotifyCommentLiked), ctx, senderId, receiverId, comment)
}

// NotifyPostCommented mocks base method.
func (m *MockWSLikeHandler) NotifyPostCommented(ctx context.Context, senderId, receiverId uuid.UUID, post *models.Post, comment *models.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyPostCommented", ctx, senderId, receiverId, post, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyPostCommented indicates an expected call of NotifyPostCommented.
func (mr *MockWSLikeHandlerMockRecorder) NotifyPostCommented(ctx, senderId, receiverId, post, comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyPostCommented", reflect.TypeOf((*MockWSLikeHandler)(nil).NotifyPostCommented), ctx, senderId, receiverId, post, comment)
}

// NotifyPostLiked mocks base method.
func (m *MockWSLikeHandler) NotifyPostLiked(ctx context.Context, senderId, receiverId uuid.UUID, post *models.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyPostLiked", ctx, senderId, receiverId, post)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyPostLiked indicates an expected call of NotifyPostLiked.
func (mr *MockWSLikeHandlerMockRecorder) NotifyPostLiked(ctx, senderId, receiverId, post interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyPostLiked", reflect.TypeOf((*MockWSLikeHandler)(nil).NotifyPostLiked), ctx, senderId, receiverId, post)
}

// MockSearchUseCase is a mock of SearchUseCase interface.
type MockSearchUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockSearchUseCaseMockRecorder
}

// MockSearchUseCaseMockRecorder is the mock recorder for MockSearchUseCase.
type MockSearchUseCaseMockRecorder struct {
	mock *MockSearchUseCase
}

// NewMockSearchUseCase creates a new mock instance.
func NewMockSearchUseCase(ctrl *gomock.Controller) *MockSearchUseCase {
	mock := &MockSearchUseCase{ctrl: ctrl}
	mock.recorder = &MockSearchUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchUseCase) EXPECT() *MockSearchUseCaseMockRecorder {
	return m.recorder
}

// SearchSimilarUser mocks base method.
func (m *MockSearchUseCase) SearchSimilarUser(ctx context.Context, toSearch string, postsCount uint) ([]models.PublicUserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchSimilarUser", ctx, toSearch, postsCount)
	ret0, _ := ret[0].([]models.PublicUserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchSimilarUser indicates an expected call of SearchSimilarUser.
func (mr *MockSearchUseCaseMockRecorder) SearchSimilarUser(ctx, toSearch, postsCount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchSimilarUser", reflect.TypeOf((*MockSearchUseCase)(nil).SearchSimilarUser), ctx, toSearch, postsCount)
}

// MockStickerUseCase is a mock of StickerUseCase interface.
type MockStickerUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockStickerUseCaseMockRecorder
}

// MockStickerUseCaseMockRecorder is the mock recorder for MockStickerUseCase.
type MockStickerUseCaseMockRecorder struct {
	mock *MockStickerUseCase
}

// NewMockStickerUseCase creates a new mock instance.
func NewMockStickerUseCase(ctrl *gomock.Controller) *MockStickerUseCase {
	mock := &MockStickerUseCase{ctrl: ctrl}
	mock.recorder = &MockStickerUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStickerUseCase) EXPECT() *MockStickerUseCaseMockRecorder {
	return m.recorder
}

// AddStickerPack mocks base method.
func (m *MockStickerUseCase) AddStickerPack(ctx context.Context, stickerPack *models.StickerPack) (*models.StickerPack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddStickerPack", ctx, stickerPack)
	ret0, _ := ret[0].(*models.StickerPack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddStickerPack indicates an expected call of AddStickerPack.
func (mr *MockStickerUseCaseMockRecorder) AddStickerPack(ctx, stickerPack interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddStickerPack", reflect.TypeOf((*MockStickerUseCase)(nil).AddStickerPack), ctx, stickerPack)
}

// DeleteStickerPack mocks base method.
func (m *MockStickerUseCase) DeleteStickerPack(ctx context.Context, userId, packId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStickerPack", ctx, userId, packId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStickerPack indicates an expected call of DeleteStickerPack.
func (mr *MockStickerUseCaseMockRecorder) DeleteStickerPack(ctx, userId, packId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStickerPack", reflect.TypeOf((*MockStickerUseCase)(nil).DeleteStickerPack), ctx, userId, packId)
}

// GetStickerPack mocks base method.
func (m *MockStickerUseCase) GetStickerPack(ctx context.Context, packId uuid.UUID) (*models.StickerPack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStickerPack", ctx, packId)
	ret0, _ := ret[0].(*models.StickerPack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStickerPack indicates an expected call of GetStickerPack.
func (mr *MockStickerUseCaseMockRecorder) GetStickerPack(ctx, packId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStickerPack", reflect.TypeOf((*MockStickerUseCase)(nil).GetStickerPack), ctx, packId)
}

// GetStickerPackByName mocks base method.
func (m *MockStickerUseCase) GetStickerPackByName(ctx context.Context, packName string) (*models.StickerPack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStickerPackByName", ctx, packName)
	ret0, _ := ret[0].(*models.StickerPack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStickerPackByName indicates an expected call of GetStickerPackByName.
func (mr *MockStickerUseCaseMockRecorder) GetStickerPackByName(ctx, packName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStickerPackByName", reflect.TypeOf((*MockStickerUseCase)(nil).GetStickerPackByName), ctx, packName)
}

// GetStickerPacks mocks base method.
func (m *MockStickerUseCase) GetStickerPacks(ctx context.Context, userId uuid.UUID, count, offset int) ([]*models.StickerPack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStickerPacks", ctx, userId, count, offset)
	ret0, _ := ret[0].([]*models.StickerPack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStickerPacks indicates an expected call of GetStickerPacks.
func (mr *MockStickerUseCaseMockRecorder) GetStickerPacks(ctx, userId, count, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStickerPacks", reflect.TypeOf((*MockStickerUseCase)(nil).GetStickerPacks), ctx, userId, count, offset)
}

// MockMessageService is a mock of MessageService interface.
type MockMessageService struct {
	ctrl     *gomock.Controller
	recorder *MockMessageServiceMockRecorder
}

// MockMessageServiceMockRecorder is the mock recorder for MockMessageService.
type MockMessageServiceMockRecorder struct {
	mock *MockMessageService
}

// NewMockMessageService creates a new mock instance.
func NewMockMessageService(ctrl *gomock.Controller) *MockMessageService {
	mock := &MockMessageService{ctrl: ctrl}
	mock.recorder = &MockMessageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageService) EXPECT() *MockMessageServiceMockRecorder {
	return m.recorder
}

// DeleteMessage mocks base method.
func (m *MockMessageService) DeleteMessage(ctx context.Context, messageId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessage", ctx, messageId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockMessageServiceMockRecorder) DeleteMessage(ctx, messageId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockMessageService)(nil).DeleteMessage), ctx, messageId)
}

// GetLastReadTs mocks base method.
func (m *MockMessageService) GetLastReadTs(ctx context.Context, chatId, userId uuid.UUID) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastReadTs", ctx, chatId, userId)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastReadTs indicates an expected call of GetLastReadTs.
func (mr *MockMessageServiceMockRecorder) GetLastReadTs(ctx, chatId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastReadTs", reflect.TypeOf((*MockMessageService)(nil).GetLastReadTs), ctx, chatId, userId)
}

// GetMessageById mocks base method.
func (m *MockMessageService) GetMessageById(ctx context.Context, messageId uuid.UUID) (*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageById", ctx, messageId)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageById indicates an expected call of GetMessageById.
func (mr *MockMessageServiceMockRecorder) GetMessageById(ctx, messageId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageById", reflect.TypeOf((*MockMessageService)(nil).GetMessageById), ctx, messageId)
}

// GetMessagesForChat mocks base method.
func (m *MockMessageService) GetMessagesForChat(ctx context.Context, chatId uuid.UUID, numMessages int, timestamp time.Time, userId uuid.UUID) ([]*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesForChat", ctx, chatId, numMessages, timestamp, userId)
	ret0, _ := ret[0].([]*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesForChat indicates an expected call of GetMessagesForChat.
func (mr *MockMessageServiceMockRecorder) GetMessagesForChat(ctx, chatId, numMessages, timestamp, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesForChat", reflect.TypeOf((*MockMessageService)(nil).GetMessagesForChat), ctx, chatId, numMessages, timestamp, userId)
}

// GetNumUnreadMessages mocks base method.
func (m *MockMessageService) GetNumUnreadMessages(ctx context.Context, chatId, userId uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNumUnreadMessages", ctx, chatId, userId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNumUnreadMessages indicates an expected call of GetNumUnreadMessages.
func (mr *MockMessageServiceMockRecorder) GetNumUnreadMessages(ctx, chatId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNumUnreadMessages", reflect.TypeOf((*MockMessageService)(nil).GetNumUnreadMessages), ctx, chatId, userId)
}

// SendMessage mocks base method.
func (m *MockMessageService) SendMessage(ctx context.Context, message *models.Message, userId uuid.UUID) (*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, message, userId)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockMessageServiceMockRecorder) SendMessage(ctx, message, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockMessageService)(nil).SendMessage), ctx, message, userId)
}

// UpdateLastReadTs mocks base method.
func (m *MockMessageService) UpdateLastReadTs(ctx context.Context, chatId, userId uuid.UUID, timestamp time.Time, userAuthId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastReadTs", ctx, chatId, userId, timestamp, userAuthId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastReadTs indicates an expected call of UpdateLastReadTs.
func (mr *MockMessageServiceMockRecorder) UpdateLastReadTs(ctx, chatId, userId, timestamp, userAuthId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastReadTs", reflect.TypeOf((*MockMessageService)(nil).UpdateLastReadTs), ctx, chatId, userId, timestamp, userAuthId)
}
