apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service-deployment
  labels:
    app: post-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: qf-post-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              name: grpc
            - containerPort: 9082
              name: metrics
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-secrets
      restartPolicy: Always