// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: profile_service.proto

package user_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	file_service "quickflow/shared/proto/file_service"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SchoolEducation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchoolEducation) Reset() {
	*x = SchoolEducation{}
	mi := &file_profile_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchoolEducation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchoolEducation) ProtoMessage() {}

func (x *SchoolEducation) ProtoReflect() protoreflect.Message {
	mi := &file_profile_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchoolEducation.ProtoReflect.Descriptor instead.
func (*SchoolEducation) Descriptor() ([]byte, []int) {
	return file_profile_service_proto_rawDescGZIP(), []int{0}
}

func (x *SchoolEducation) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *SchoolEducation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UniversityEducation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	City           string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	University     string                 `protobuf:"bytes,2,opt,name=university,proto3" json:"university,omitempty"`
	Faculty        string                 `protobuf:"bytes,3,opt,name=faculty,proto3" json:"faculty,omitempty"`
	GraduationYear int32                  `protobuf:"varint,4,opt,name=graduation_year,json=graduationYear,proto3" json:"graduation_year,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UniversityEducation) Reset() {
	*x = UniversityEducation{}
	mi := &file_profile_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniversityEducation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniversityEducation) ProtoMessage() {}

func (x *UniversityEducation) ProtoReflect() protoreflect.Message {
	mi := &file_profile_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniversityEducation.ProtoReflect.Descriptor instead.
func (*UniversityEducation) Descriptor() ([]byte, []int) {
	return file_profile_service_proto_rawDescGZIP(), []int{1}
}

func (x *UniversityEducation) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UniversityEducation) GetUniversity() string {
	if x != nil {
		return x.University
	}
	return ""
}

func (x *UniversityEducation) GetFaculty() string {
	if x != nil {
		return x.Faculty
	}
	return ""
}

func (x *UniversityEducation) GetGraduationYear() int32 {
	if x != nil {
		return x.GraduationYear
	}
	return 0
}

type ContactInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactInfo) Reset() {
	*x = ContactInfo{}
	mi := &file_profile_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactInfo) ProtoMessage() {}

func (x *ContactInfo) ProtoReflect() protoreflect.Message {
	mi := &file_profile_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactInfo.ProtoReflect.Descriptor instead.
func (*ContactInfo) Descriptor() ([]byte, []int) {
	return file_profile_service_proto_rawDescGZIP(), []int{2}
}

func (x *ContactInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ContactInfo) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *ContactInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type BasicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Firstname     string                 `protobuf:"bytes,3,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname      string                 `protobuf:"bytes,4,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Sex           int32                  `protobuf:"varint,5,opt,name=sex,proto3" json:"sex,omitempty"`
	BirthDate     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Bio           string                 `protobuf:"bytes,7,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,8,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,9,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicInfo) Reset() {
	*x = BasicInfo{}
	mi := &file_profile_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicInfo) ProtoMessage() {}

func (x *BasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_profile_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicInfo.ProtoReflect.Descriptor instead.
func (*BasicInfo) Descriptor() ([]byte, []int) {
	return file_profile_service_proto_rawDescGZIP(), []int{3}
}

func (x *BasicInfo) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *BasicInfo) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *BasicInfo) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *BasicInfo) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *BasicInfo) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *BasicInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *BasicInfo) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

type Profile struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username            string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	BasicInfo           *BasicInfo             `protobuf:"bytes,3,opt,name=basic_info,json=basicInfo,proto3" json:"basic_info,omitempty"`
	SchoolEducation     *SchoolEducation       `protobuf:"bytes,10,opt,name=school_education,json=schoolEducation,proto3" json:"school_education,omitempty"`
	UniversityEducation *UniversityEducation   `protobuf:"bytes,11,opt,name=university_education,json=universityEducation,proto3" json:"university_education,omitempty"`
	ContactInfo         *ContactInfo           `protobuf:"bytes,12,opt,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"`
	Avatar              *file_service.File     `protobuf:"bytes,13,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Cover               *file_service.File     `protobuf:"bytes,14,opt,name=cover,proto3" json:"cover,omitempty"`
	LastSeen            *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_profile_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_profile_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_profile_service_proto_rawDescGZIP(), []int{4}
}

func (x *Profile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Profile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Profile) GetBasicInfo() *BasicInfo {
	if x != nil {
		return x.BasicInfo
	}
	return nil
}

func (x *Profile) GetSchoolEducation() *SchoolEducation {
	if x != nil {
		return x.SchoolEducation
	}
	return nil
}

func (x *Profile) GetUniversityEducation() *UniversityEducation {
	if x != nil {
		return x.UniversityEducation
	}
	return nil
}

func (x *Profile) GetContactInfo() *ContactInfo {
	if x != nil {
		return x.ContactInfo
	}
	return nil
}

func (x *Profile) GetAvatar() *file_service.File {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *Profile) GetCover() *file_service.File {
	if x != nil {
		return x.Cover
	}
	return nil
}

func (x *Profile) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type PublicUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Firstname     string                 `protobuf:"bytes,3,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname      string                 `protobuf:"bytes,4,opt,name=lastname,proto3" json:"lastname,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicUserInfo) Reset() {
	*x = PublicUserInfo{}
	mi := &file_profile_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicUserInfo) ProtoMessage() {}

func (x *PublicUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_profile_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicUserInfo.ProtoReflect.Descriptor instead.
func (*PublicUserInfo) Descriptor() ([]byte, []int) {
	return file_profile_service_proto_rawDescGZIP(), []int{5}
}

func (x *PublicUserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublicUserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PublicUserInfo) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *PublicUserInfo) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *PublicUserInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *PublicUserInfo) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type CreateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_profile_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateProfileRequest) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type CreateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_profile_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_profile_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProfileRequest) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_profile_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_profile_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_profile_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type GetProfileByUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByUsernameRequest) Reset() {
	*x = GetProfileByUsernameRequest{}
	mi := &file_profile_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByUsernameRequest) ProtoMessage() {}

func (x *GetProfileByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByUsernameRequest.ProtoReflect.Descriptor instead.
func (*GetProfileByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_profile_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetProfileByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetProfileByUsernameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByUsernameResponse) Reset() {
	*x = GetProfileByUsernameResponse{}
	mi := &file_profile_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByUsernameResponse) ProtoMessage() {}

func (x *GetProfileByUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByUsernameResponse.ProtoReflect.Descriptor instead.
func (*GetProfileByUsernameResponse) Descriptor() ([]byte, []int) {
	return file_profile_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetProfileByUsernameResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UpdateLastSeenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLastSeenRequest) Reset() {
	*x = UpdateLastSeenRequest{}
	mi := &file_profile_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLastSeenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLastSeenRequest) ProtoMessage() {}

func (x *UpdateLastSeenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLastSeenRequest.ProtoReflect.Descriptor instead.
func (*UpdateLastSeenRequest) Descriptor() ([]byte, []int) {
	return file_profile_service_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateLastSeenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateLastSeenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLastSeenResponse) Reset() {
	*x = UpdateLastSeenResponse{}
	mi := &file_profile_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLastSeenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLastSeenResponse) ProtoMessage() {}

func (x *UpdateLastSeenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLastSeenResponse.ProtoReflect.Descriptor instead.
func (*UpdateLastSeenResponse) Descriptor() ([]byte, []int) {
	return file_profile_service_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateLastSeenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetPublicUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicUserInfoRequest) Reset() {
	*x = GetPublicUserInfoRequest{}
	mi := &file_profile_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicUserInfoRequest) ProtoMessage() {}

func (x *GetPublicUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPublicUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_profile_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetPublicUserInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPublicUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *PublicUserInfo        `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicUserInfoResponse) Reset() {
	*x = GetPublicUserInfoResponse{}
	mi := &file_profile_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicUserInfoResponse) ProtoMessage() {}

func (x *GetPublicUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetPublicUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_profile_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetPublicUserInfoResponse) GetUserInfo() *PublicUserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type GetPublicUsersInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicUsersInfoRequest) Reset() {
	*x = GetPublicUsersInfoRequest{}
	mi := &file_profile_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicUsersInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicUsersInfoRequest) ProtoMessage() {}

func (x *GetPublicUsersInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicUsersInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPublicUsersInfoRequest) Descriptor() ([]byte, []int) {
	return file_profile_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetPublicUsersInfoRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetPublicUsersInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsersInfo     []*PublicUserInfo      `protobuf:"bytes,1,rep,name=users_info,json=usersInfo,proto3" json:"users_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicUsersInfoResponse) Reset() {
	*x = GetPublicUsersInfoResponse{}
	mi := &file_profile_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicUsersInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicUsersInfoResponse) ProtoMessage() {}

func (x *GetPublicUsersInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicUsersInfoResponse.ProtoReflect.Descriptor instead.
func (*GetPublicUsersInfoResponse) Descriptor() ([]byte, []int) {
	return file_profile_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetPublicUsersInfoResponse) GetUsersInfo() []*PublicUserInfo {
	if x != nil {
		return x.UsersInfo
	}
	return nil
}

var File_profile_service_proto protoreflect.FileDescriptor

const file_profile_service_proto_rawDesc = "" +
	"\n" +
	"\x15profile_service.proto\x12\x0fprofile_service\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ffile_service/file_service.proto\"9\n" +
	"\x0fSchoolEducation\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8c\x01\n" +
	"\x13UniversityEducation\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x1e\n" +
	"\n" +
	"university\x18\x02 \x01(\tR\n" +
	"university\x12\x18\n" +
	"\afaculty\x18\x03 \x01(\tR\afaculty\x12'\n" +
	"\x0fgraduation_year\x18\x04 \x01(\x05R\x0egraduationYear\"Z\n" +
	"\vContactInfo\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12!\n" +
	"\fphone_number\x18\x02 \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\xe0\x01\n" +
	"\tBasicInfo\x12\x1c\n" +
	"\tfirstname\x18\x03 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x04 \x01(\tR\blastname\x12\x10\n" +
	"\x03sex\x18\x05 \x01(\x05R\x03sex\x129\n" +
	"\n" +
	"birth_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tbirthDate\x12\x10\n" +
	"\x03bio\x18\a \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\b \x01(\tR\tavatarUrl\x12\x1b\n" +
	"\tcover_url\x18\t \x01(\tR\bcoverUrl\"\xe6\x03\n" +
	"\aProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x129\n" +
	"\n" +
	"basic_info\x18\x03 \x01(\v2\x1a.profile_service.BasicInfoR\tbasicInfo\x12K\n" +
	"\x10school_education\x18\n" +
	" \x01(\v2 .profile_service.SchoolEducationR\x0fschoolEducation\x12W\n" +
	"\x14university_education\x18\v \x01(\v2$.profile_service.UniversityEducationR\x13universityEducation\x12?\n" +
	"\fcontact_info\x18\f \x01(\v2\x1c.profile_service.ContactInfoR\vcontactInfo\x12*\n" +
	"\x06avatar\x18\r \x01(\v2\x12.file_service.FileR\x06avatar\x12(\n" +
	"\x05cover\x18\x0e \x01(\v2\x12.file_service.FileR\x05cover\x127\n" +
	"\tlast_seen\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\"\xce\x01\n" +
	"\x0ePublicUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1c\n" +
	"\tfirstname\x18\x03 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x04 \x01(\tR\blastname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\x127\n" +
	"\tlast_seen\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\"J\n" +
	"\x14CreateProfileRequest\x122\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.profile_service.ProfileR\aprofile\"K\n" +
	"\x15CreateProfileResponse\x122\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.profile_service.ProfileR\aprofile\"J\n" +
	"\x14UpdateProfileRequest\x122\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.profile_service.ProfileR\aprofile\"K\n" +
	"\x15UpdateProfileResponse\x122\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.profile_service.ProfileR\aprofile\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"H\n" +
	"\x12GetProfileResponse\x122\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.profile_service.ProfileR\aprofile\"9\n" +
	"\x1bGetProfileByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"R\n" +
	"\x1cGetProfileByUsernameResponse\x122\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.profile_service.ProfileR\aprofile\"0\n" +
	"\x15UpdateLastSeenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"2\n" +
	"\x16UpdateLastSeenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"3\n" +
	"\x18GetPublicUserInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"Y\n" +
	"\x19GetPublicUserInfoResponse\x12<\n" +
	"\tuser_info\x18\x01 \x01(\v2\x1f.profile_service.PublicUserInfoR\buserInfo\"6\n" +
	"\x19GetPublicUsersInfoRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"\\\n" +
	"\x1aGetPublicUsersInfoResponse\x12>\n" +
	"\n" +
	"users_info\x18\x01 \x03(\v2\x1f.profile_service.PublicUserInfoR\tusersInfo2\xda\x05\n" +
	"\x0eProfileService\x12^\n" +
	"\rCreateProfile\x12%.profile_service.CreateProfileRequest\x1a&.profile_service.CreateProfileResponse\x12^\n" +
	"\rUpdateProfile\x12%.profile_service.UpdateProfileRequest\x1a&.profile_service.UpdateProfileResponse\x12U\n" +
	"\n" +
	"GetProfile\x12\".profile_service.GetProfileRequest\x1a#.profile_service.GetProfileResponse\x12s\n" +
	"\x14GetProfileByUsername\x12,.profile_service.GetProfileByUsernameRequest\x1a-.profile_service.GetProfileByUsernameResponse\x12a\n" +
	"\x0eUpdateLastSeen\x12&.profile_service.UpdateLastSeenRequest\x1a'.profile_service.UpdateLastSeenResponse\x12j\n" +
	"\x11GetPublicUserInfo\x12).profile_service.GetPublicUserInfoRequest\x1a*.profile_service.GetPublicUserInfoResponse\x12m\n" +
	"\x12GetPublicUsersInfo\x12*.profile_service.GetPublicUsersInfoRequest\x1a+.profile_service.GetPublicUsersInfoResponseB%Z#quickflow/shared/proto/user_serviceb\x06proto3"

var (
	file_profile_service_proto_rawDescOnce sync.Once
	file_profile_service_proto_rawDescData []byte
)

func file_profile_service_proto_rawDescGZIP() []byte {
	file_profile_service_proto_rawDescOnce.Do(func() {
		file_profile_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_service_proto_rawDesc), len(file_profile_service_proto_rawDesc)))
	})
	return file_profile_service_proto_rawDescData
}

var file_profile_service_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_profile_service_proto_goTypes = []any{
	(*SchoolEducation)(nil),              // 0: profile_service.SchoolEducation
	(*UniversityEducation)(nil),          // 1: profile_service.UniversityEducation
	(*ContactInfo)(nil),                  // 2: profile_service.ContactInfo
	(*BasicInfo)(nil),                    // 3: profile_service.BasicInfo
	(*Profile)(nil),                      // 4: profile_service.Profile
	(*PublicUserInfo)(nil),               // 5: profile_service.PublicUserInfo
	(*CreateProfileRequest)(nil),         // 6: profile_service.CreateProfileRequest
	(*CreateProfileResponse)(nil),        // 7: profile_service.CreateProfileResponse
	(*UpdateProfileRequest)(nil),         // 8: profile_service.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),        // 9: profile_service.UpdateProfileResponse
	(*GetProfileRequest)(nil),            // 10: profile_service.GetProfileRequest
	(*GetProfileResponse)(nil),           // 11: profile_service.GetProfileResponse
	(*GetProfileByUsernameRequest)(nil),  // 12: profile_service.GetProfileByUsernameRequest
	(*GetProfileByUsernameResponse)(nil), // 13: profile_service.GetProfileByUsernameResponse
	(*UpdateLastSeenRequest)(nil),        // 14: profile_service.UpdateLastSeenRequest
	(*UpdateLastSeenResponse)(nil),       // 15: profile_service.UpdateLastSeenResponse
	(*GetPublicUserInfoRequest)(nil),     // 16: profile_service.GetPublicUserInfoRequest
	(*GetPublicUserInfoResponse)(nil),    // 17: profile_service.GetPublicUserInfoResponse
	(*GetPublicUsersInfoRequest)(nil),    // 18: profile_service.GetPublicUsersInfoRequest
	(*GetPublicUsersInfoResponse)(nil),   // 19: profile_service.GetPublicUsersInfoResponse
	(*timestamppb.Timestamp)(nil),        // 20: google.protobuf.Timestamp
	(*file_service.File)(nil),            // 21: file_service.File
}
var file_profile_service_proto_depIdxs = []int32{
	20, // 0: profile_service.BasicInfo.birth_date:type_name -> google.protobuf.Timestamp
	3,  // 1: profile_service.Profile.basic_info:type_name -> profile_service.BasicInfo
	0,  // 2: profile_service.Profile.school_education:type_name -> profile_service.SchoolEducation
	1,  // 3: profile_service.Profile.university_education:type_name -> profile_service.UniversityEducation
	2,  // 4: profile_service.Profile.contact_info:type_name -> profile_service.ContactInfo
	21, // 5: profile_service.Profile.avatar:type_name -> file_service.File
	21, // 6: profile_service.Profile.cover:type_name -> file_service.File
	20, // 7: profile_service.Profile.last_seen:type_name -> google.protobuf.Timestamp
	20, // 8: profile_service.PublicUserInfo.last_seen:type_name -> google.protobuf.Timestamp
	4,  // 9: profile_service.CreateProfileRequest.profile:type_name -> profile_service.Profile
	4,  // 10: profile_service.CreateProfileResponse.profile:type_name -> profile_service.Profile
	4,  // 11: profile_service.UpdateProfileRequest.profile:type_name -> profile_service.Profile
	4,  // 12: profile_service.UpdateProfileResponse.profile:type_name -> profile_service.Profile
	4,  // 13: profile_service.GetProfileResponse.profile:type_name -> profile_service.Profile
	4,  // 14: profile_service.GetProfileByUsernameResponse.profile:type_name -> profile_service.Profile
	5,  // 15: profile_service.GetPublicUserInfoResponse.user_info:type_name -> profile_service.PublicUserInfo
	5,  // 16: profile_service.GetPublicUsersInfoResponse.users_info:type_name -> profile_service.PublicUserInfo
	6,  // 17: profile_service.ProfileService.CreateProfile:input_type -> profile_service.CreateProfileRequest
	8,  // 18: profile_service.ProfileService.UpdateProfile:input_type -> profile_service.UpdateProfileRequest
	10, // 19: profile_service.ProfileService.GetProfile:input_type -> profile_service.GetProfileRequest
	12, // 20: profile_service.ProfileService.GetProfileByUsername:input_type -> profile_service.GetProfileByUsernameRequest
	14, // 21: profile_service.ProfileService.UpdateLastSeen:input_type -> profile_service.UpdateLastSeenRequest
	16, // 22: profile_service.ProfileService.GetPublicUserInfo:input_type -> profile_service.GetPublicUserInfoRequest
	18, // 23: profile_service.ProfileService.GetPublicUsersInfo:input_type -> profile_service.GetPublicUsersInfoRequest
	7,  // 24: profile_service.ProfileService.CreateProfile:output_type -> profile_service.CreateProfileResponse
	9,  // 25: profile_service.ProfileService.UpdateProfile:output_type -> profile_service.UpdateProfileResponse
	11, // 26: profile_service.ProfileService.GetProfile:output_type -> profile_service.GetProfileResponse
	13, // 27: profile_service.ProfileService.GetProfileByUsername:output_type -> profile_service.GetProfileByUsernameResponse
	15, // 28: profile_service.ProfileService.UpdateLastSeen:output_type -> profile_service.UpdateLastSeenResponse
	17, // 29: profile_service.ProfileService.GetPublicUserInfo:output_type -> profile_service.GetPublicUserInfoResponse
	19, // 30: profile_service.ProfileService.GetPublicUsersInfo:output_type -> profile_service.GetPublicUsersInfoResponse
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_profile_service_proto_init() }
func file_profile_service_proto_init() {
	if File_profile_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_service_proto_rawDesc), len(file_profile_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_service_proto_goTypes,
		DependencyIndexes: file_profile_service_proto_depIdxs,
		MessageInfos:      file_profile_service_proto_msgTypes,
	}.Build()
	File_profile_service_proto = out.File
	file_profile_service_proto_goTypes = nil
	file_profile_service_proto_depIdxs = nil
}
