services:

  gateway:
    build:
      context: ../backend
      dockerfile: gateway/Dockerfile
    container_name: ${GATEWAY_NAME:-gateway}
    ports:
      - "${GATEWAY_PORT:-8080}:8080"
    volumes:
      - ../deploy/config:/config
    depends_on:
      # Условия остаются, но имена сервисов тоже можно параметризовать
      - post_service
      - user_service
      - file_service
      - messenger_service
      #- feedback_service
      - friends_service
      - community_service
    restart: unless-stopped
    environment:
      RUNNING_IN_CONTAINER: true
    env_file:
      - ${ENV_FILE:-.env}
    networks:
      - backend-network

  file_service:
    build:
      context: ../backend
      dockerfile: file_service/Dockerfile
    container_name: ${FILE_SERVICE_NAME:-file_service}
    ports:
      - "${FILE_SERVICE_PORT:-8081}:8081"
    volumes:
      - ../deploy/config:/config
    restart: unless-stopped
    environment:
      RUNNING_IN_CONTAINER: true
    env_file:
      - ${ENV_FILE:-.env}
    networks:
      - backend-network

  post_service:
    build:
      context: ../backend
      dockerfile: post_service/Dockerfile
    container_name: ${POST_SERVICE_NAME:-post_service}
    ports:
      - "${POST_SERVICE_PORT:-8082}:8082"
    volumes:
      - ../deploy/config:/config
    restart: unless-stopped
    env_file:
      - ${ENV_FILE:-.env}
    networks:
      - backend-network

  user_service:
    build:
      context: ../backend
      dockerfile: user_service/Dockerfile
    container_name: ${USER_SERVICE_NAME:-user_service}
    ports:
      - "${USER_SERVICE_PORT:-8083}:8083"
    volumes:
      - ../deploy/config:/config
    restart: unless-stopped
    env_file:
      - ${ENV_FILE:-.env}
    networks:
      - backend-network

  messenger_service:
    build:
      context: ../backend
      dockerfile: messenger_service/Dockerfile
    container_name: ${MESSENGER_SERVICE_NAME:-messenger_service}
    ports:
      - "${MESSENGER_SERVICE_PORT:-8084}:8084"
    volumes:
      - ../deploy/config:/config
    restart: unless-stopped
    env_file:
      - ${ENV_FILE:-.env}
    networks:
      - backend-network

#  feedback_service:
#    build:
#      context: ../backend
#      dockerfile: feedback_service/Dockerfile
#    container_name: ${FEEDBACK_SERVICE_NAME:-feedback_service}
#    ports:
#      - "${FEEDBACK_SERVICE_PORT:-8085}:8085"
#    volumes:
#      - ../deploy/config:/config
#    restart: unless-stopped
#    env_file:
#      - ${ENV_FILE:-.env}
#    networks:
#      - backend-network

  friends_service:
    build:
      context: ../backend
      dockerfile: ../backend/friends_service/Dockerfile
    container_name: ${FRIENDS_SERVICE_NAME:-friends_service}
    ports:
      - "${FRIENDS_SERVICE_PORT:-8086}:8086"
    volumes:
      - ../deploy/config:/config
    restart: unless-stopped
    env_file:
      - ${ENV_FILE:-.env}
    networks:
      - backend-network

  community_service:
    build:
      context: ../backend
      dockerfile: community_service/Dockerfile
    container_name: ${COMMUNITY_SERVICE_NAME:-community_service}
    ports:
      - "${COMMUNITY_SERVICE_PORT:-8087}:8087"
    volumes:
      - ../deploy/config:/config
    restart: unless-stopped
    env_file:
      - ${ENV_FILE:-.env}
    networks:
      - backend-network

networks:
  backend-network:
    name: "backend-network"
    external: true


# TODO: unload + rm ~/Library/LaunchAgents/com.quickflow.docker-compose.plist
