apiVersion: apps/v1
kind: Deployment
metadata:
  name: friends-service-deployment
  labels:
    app: friends-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: friends-service
  template:
    metadata:
      labels:
        app: friends-service
    spec:
      containers:
        - name: friends-service
          image: qf-friends-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-secrets
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: friends-service # DNS-имя для доступа внутри кластера
spec:
  selector:
    app: friends-service
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086