apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      volumes:
        - name: feeder-config-volume
          configMap:
            name: feeder-config
        - name: cors-config-volume
          configMap:
            name: cors-config
        - name: minio-config-volume
          configMap:
            name: minio-config
        - name: validation-config-volume
          configMap:
            name: gateway-validation-config
      containers:
        - name: gateway
          image: qf-gateway:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-secrets
          volumeMounts:
            - name: feeder-config-volume
              mountPath: /config/feeder
              readOnly: true
            - name: cors-config-volume
              mountPath: /config/cors
              readOnly: true
            - name: minio-config-volume
              mountPath: /config/minio
              readOnly: true
            - name: validation-config-volume
              mountPath: /config/validation
              readOnly: true
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080