FROM golang:1.24 AS tester

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./file_service ./file_service
COPY ./shared ./shared
COPY ./utils ./utils
COPY ./config ./config
COPY ./metrics ./metrics
COPY ./pkg ./pkg

CMD ["go", "test", "./file_service/..."]
