apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Базовые ресурсы
resources:
- ../../base
- namespace.yaml

# Специфичные для production настройки
namespace: quickflow-prod

# Увеличение реплик для production
patches:
- path: replicas-patch.yaml

# Генерация configmap для production
configMapGenerator:
- name: prod-config
  literals:
  - ENV=production
  - DEBUG=false