apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- name: file-service-config
  files:
  - minio-config=config/minio/config.toml
  - validation-config=config/validation/config.toml