apiVersion: v1
kind: Service
metadata:
  name: file-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9081"
spec:
  selector:
    app: file-service
  ports:
    - name: grpc
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: metrics
      protocol: TCP
      port: 9081
      targetPort: 9081