apiVersion: v1
kind: Service
metadata:
  name: friends-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9086"
spec:
  selector:
    app: friends-service
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
      name: grpc
    - protocol: TCP
      port: 9086
      targetPort: 9086
      name: metrics