FROM golang:1.24 AS tester

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./community_service ./community_service
COPY ./shared ./shared
COPY ./utils ./utils
COPY ./config ./config
COPY ./metrics ./metrics

CMD ["go", "test", "-v", "./community_service/..."]
