// Code generated by MockGen. DO NOT EDIT.
// Source: ./feedback_service/internal/usecase/feedback-usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "quickflow/shared/models"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockFeedbackRepository is a mock of FeedbackRepository interface.
type MockFeedbackRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFeedbackRepositoryMockRecorder
}

// MockFeedbackRepositoryMockRecorder is the mock recorder for MockFeedbackRepository.
type MockFeedbackRepositoryMockRecorder struct {
	mock *MockFeedbackRepository
}

// NewMockFeedbackRepository creates a new mock instance.
func NewMockFeedbackRepository(ctrl *gomock.Controller) *MockFeedbackRepository {
	mock := &MockFeedbackRepository{ctrl: ctrl}
	mock.recorder = &MockFeedbackRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedbackRepository) EXPECT() *MockFeedbackRepositoryMockRecorder {
	return m.recorder
}

// GetAllFeedbackType mocks base method.
func (m *MockFeedbackRepository) GetAllFeedbackType(ctx context.Context, feedbackType models.FeedbackType, ts time.Time, count int) ([]models.Feedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllFeedbackType", ctx, feedbackType, ts, count)
	ret0, _ := ret[0].([]models.Feedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllFeedbackType indicates an expected call of GetAllFeedbackType.
func (mr *MockFeedbackRepositoryMockRecorder) GetAllFeedbackType(ctx, feedbackType, ts, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllFeedbackType", reflect.TypeOf((*MockFeedbackRepository)(nil).GetAllFeedbackType), ctx, feedbackType, ts, count)
}

// SaveFeedback mocks base method.
func (m *MockFeedbackRepository) SaveFeedback(ctx context.Context, feedback *models.Feedback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFeedback", ctx, feedback)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFeedback indicates an expected call of SaveFeedback.
func (mr *MockFeedbackRepositoryMockRecorder) SaveFeedback(ctx, feedback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFeedback", reflect.TypeOf((*MockFeedbackRepository)(nil).SaveFeedback), ctx, feedback)
}
