apiVersion: v1
kind: Service
metadata:
  name: community-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9087"
spec:
  selector:
    app: community-service
  ports:
    - name: grpc
      protocol: TCP
      port: 8087
      targetPort: 8087
    - name: metrics
      protocol: TCP
      port: 9087
      targetPort: 9087