apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- name: gateway-config
  files:
  - feeder-config=config/feeder/config.toml
  - cors-config=config/cors/config.toml
  - minio-config=config/minio/config.toml
  - validation-config=config/validation/config.toml