FROM golang:1.24 AS tester

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./feedback_service ./feedback_service
COPY ./shared ./shared
COPY ./utils ./utils
COPY ./config ./config
COPY ./metrics ./metrics

CMD ["go", "test", "./feedback_service/..."]
