apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: quickflow
data:
  # Имена сервисов в Kubernetes!
  POSTGRES_HOST: "postgres-postgresql"
  POSTGRES_USER: "quickflow_admin"
  POSTGRES_DB: "quickflow_db"
  REDIS_HOST: "redis-master"
  MINIO_HOST: "minio"
  # : ": ": " Database & Redis : ": ": "
  DATABASE_URL: "postgresql://quickflow_admin:SuperSecurePassword1@postgres:5432/quickflow_db"
  REDIS_URL: "redis:6379"
  DOMAIN: "localhost"
  
  MINIO_ROOT_USER: "admin"
  MINIO_POSTS_BUCKET_NAME: "posts"
  MINIO_PROFILE_BUCKET_NAME: "profile-images"
  MINIO_ATTACHMENTS_BUCKET_NAME: "attachments"
  MINIO_STICKERS_BUCKET_NAME: "stickers"
  MINIO_INTERNAL_ENDPOINT: "minio:9000"

  GATEWAY_NAME: "gateway"
  FILE_SERVICE_NAME: "file_service"
  POST_SERVICE_NAME: "post_service"
  USER_SERVICE_NAME: "user_service"
  MESSENGER_SERVICE_NAME: "messenger_service"
  FEEDBACK_SERVICE_NAME: "feedback_service"
  FRIENDS_SERVICE_NAME: "friends_service"
  COMMUNITY_SERVICE_NAME: "community_service"
  
  GATEWAY_PORT: "8080"
  FILE_SERVICE_PORT: "8081"
  POST_SERVICE_PORT: "8082"
  USER_SERVICE_PORT: "8083"
  MESSENGER_SERVICE_PORT: "8084"
  FEEDBACK_SERVICE_PORT: "8085"
  FRIENDS_SERVICE_PORT: "8086"
  COMMUNITY_SERVICE_PORT: "8087"
  
  RUNNING_IN_CONTAINER: "true"
  
#  # клиентские имена и порты
#  AVAILABLE_GATEWAY_NAME: "gateway"
#  AVAILABLE_FILE_SERVICE_NAME: "file_service"
#  AVAILABLE_POST_SERVICE_NAME: "post_service"
#  AVAILABLE_USER_SERVICE_NAME: "user_service"
#  AVAILABLE_MESSENGER_SERVICE_NAME: "messenger_service"
#  AVAILABLE_FEEDBACK_SERVICE_NAME: "feedback_service"
#  AVAILABLE_FRIENDS_SERVICE_NAME: "friends_service"
#  AVAILABLE_COMMUNITY_SERVICE_NAME: "community_service"
#
#  AVAILABLE_GATEWAY_PORT: "8080"
#  AVAILABLE_FILE_SERVICE_PORT: "8081"
#  AVAILABLE_POST_SERVICE_PORT: "8082"
#  AVAILABLE_USER_SERVICE_PORT: "8083"
#  AVAILABLE_MESSENGER_SERVICE_PORT: "8084"
#  AVAILABLE_FEEDBACK_SERVICE_PORT: "8085"
#  AVAILABLE_FRIENDS_SERVICE_PORT: "8086"
#  AVAILABLE_COMMUNITY_SERVICE_PORT: "8087"
